//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class CADisplayLink, NSMutableArray, NSString, NSTimer, SWCity, UIButton, UIImageView, UITableView;
@protocol SWTipsViewDelegate;

@interface SWTipsView : UIView <UITableViewDelegate, UITableViewDataSource>
{
    _Bool _isFirstIn;
    _Bool _isAnimation;
    CDUnknownBlockType _closeHandler;
    id <SWTipsViewDelegate> _tipDelegate;
    NSString *_tipId;
    NSString *_tipContent;
    SWCity *_city;
    NSMutableArray *_models;
    UITableView *_tableView;
    UIImageView *_bgImgView;
    UIButton *_closeBtn;
    NSTimer *_timer;
    CADisplayLink *_displayLink;
    NSMutableArray *_showDataSource;
    long long _curIndex;
}

+ (id)tipsWithData:(id)arg1;
@property(nonatomic) _Bool isAnimation; // @synthesize isAnimation=_isAnimation;
@property(nonatomic) _Bool isFirstIn; // @synthesize isFirstIn=_isFirstIn;
@property(nonatomic) long long curIndex; // @synthesize curIndex=_curIndex;
@property(retain, nonatomic) NSMutableArray *showDataSource; // @synthesize showDataSource=_showDataSource;
@property(retain, nonatomic) CADisplayLink *displayLink; // @synthesize displayLink=_displayLink;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) UIButton *closeBtn; // @synthesize closeBtn=_closeBtn;
@property(retain, nonatomic) UIImageView *bgImgView; // @synthesize bgImgView=_bgImgView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSMutableArray *models; // @synthesize models=_models;
@property(retain, nonatomic) SWCity *city; // @synthesize city=_city;
@property(readonly, nonatomic) NSString *tipContent; // @synthesize tipContent=_tipContent;
@property(retain, nonatomic) NSString *tipId; // @synthesize tipId=_tipId;
@property(nonatomic) __weak id <SWTipsViewDelegate> tipDelegate; // @synthesize tipDelegate=_tipDelegate;
@property(copy, nonatomic) CDUnknownBlockType closeHandler; // @synthesize closeHandler=_closeHandler;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)timerAction;
- (void)displaylinkAction:(id)arg1;
- (void)closeBtnClicked:(id)arg1;
- (void)upLoadShowWithIndex:(long long)arg1;
- (_Bool)isShowed;
- (void)hiddenWithAnimation:(_Bool)arg1 handler:(CDUnknownBlockType)arg2;
- (void)showWithAnimation:(_Bool)arg1 handler:(CDUnknownBlockType)arg2;
- (void)stopDisplayLink;
- (void)startDisplayLink;
- (void)stopAnimation;
- (void)startAnimation;
- (void)layoutSubviews;
- (void)handleShowData;
- (void)loadDatas:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

