//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKit.h>

@class NSString;

@interface HWQuestionOptionModel : NSObject
{
    NSString *_question_option_id;
    NSString *_question_option_name;
}

@property(retain, nonatomic) NSString *question_option_name; // @synthesize question_option_name=_question_option_name;
@property(retain, nonatomic) NSString *question_option_id; // @synthesize question_option_id=_question_option_id;
- (id)attributeMapDictionary;

@end

