//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKit.h>

NSString *result_id;

@class NSMutableArray, NSString;

@interface HWQuestionsModel : NSObject
{
    NSString *_totalCount;
    NSString *_questionid;
    NSString *_question;
    NSString *_questiontype;
    NSString *_questiontype_text;
    NSString *_questionselectnumber;
    NSMutableArray *_userAnswer;
    NSString *_userAnswerStr;
    NSMutableArray *_tkselect;
    NSString *_tkselectStr;
    NSString *_trueanswer;
    NSString *_questiondescribe;
    NSString *_page;
    NSString *_cellHeight;
    NSString *_problem_type;
    NSString *_pop_time;
    NSString *_coursetest_id;
    NSString *_isAppearQuizzes;
    NSString *_isShowJump;
}

+ (id)getQuestionArrayWithDic:(id)arg1;
+ (id)getQuizzesArrayWithDic:(id)arg1;
@property(retain, nonatomic) NSString *isShowJump; // @synthesize isShowJump=_isShowJump;
@property(retain, nonatomic) NSString *isAppearQuizzes; // @synthesize isAppearQuizzes=_isAppearQuizzes;
@property(retain, nonatomic) NSString *coursetest_id; // @synthesize coursetest_id=_coursetest_id;
@property(retain, nonatomic) NSString *pop_time; // @synthesize pop_time=_pop_time;
@property(retain, nonatomic) NSString *problem_type; // @synthesize problem_type=_problem_type;
@property(copy, nonatomic) NSString *cellHeight; // @synthesize cellHeight=_cellHeight;
@property(copy, nonatomic) NSString *page; // @synthesize page=_page;
@property(copy, nonatomic) NSString *questiondescribe; // @synthesize questiondescribe=_questiondescribe;
@property(copy, nonatomic) NSString *trueanswer; // @synthesize trueanswer=_trueanswer;
@property(retain, nonatomic) NSString *tkselectStr; // @synthesize tkselectStr=_tkselectStr;
@property(retain, nonatomic) NSMutableArray *tkselect; // @synthesize tkselect=_tkselect;
@property(retain, nonatomic) NSString *userAnswerStr; // @synthesize userAnswerStr=_userAnswerStr;
@property(retain, nonatomic) NSMutableArray *userAnswer; // @synthesize userAnswer=_userAnswer;
@property(copy, nonatomic) NSString *questionselectnumber; // @synthesize questionselectnumber=_questionselectnumber;
@property(copy, nonatomic) NSString *questiontype_text; // @synthesize questiontype_text=_questiontype_text;
@property(copy, nonatomic) NSString *questiontype; // @synthesize questiontype=_questiontype;
@property(copy, nonatomic) NSString *question; // @synthesize question=_question;
@property(copy, nonatomic) NSString *questionid; // @synthesize questionid=_questionid;
@property(copy, nonatomic) NSString *totalCount; // @synthesize totalCount=_totalCount;
- (id)attributeMapDictionary;

@end

