//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKit.h>

@class HYAnswerDataManager, HYWApplyLessonCredentialManager, HYWCourseLearningListModel, HYWCourseLearningVCModel, HYWVideoPlayViewStatusModel, ITTImageView, NSMutableArray, NSString, UIButton, UILabel, UITableView, UIView, YYLabel;

@interface HYWVideoListAndNoteListViewController : NSObject
{
    HYWApplyLessonCredentialManager *_applyManager;
    UITableView *_tableView;
    UIButton *_videoButton;
    UIView *_lineView;
    UIView *_commentView;
    UIView *_examView;
    UIView *_applyView;
    UIButton *_examBtn;
    UIView *_lessonHeaderView;
    UILabel *_lessonNameLabel;
    UILabel *_lessonLevelLabel;
    UILabel *_hospitalLabel;
    UILabel *_peopleNameLabel;
    UILabel *_peopleNumLabel;
    UILabel *_starLabel;
    UIView *_starView;
    UIView *_lessonFooterView;
    UILabel *_desHospitalLabel;
    UILabel *_desNameLabel;
    ITTImageView *_footerImageView;
    UIView *_videoFooterView;
    UILabel *_teacherIntrLabel;
    UILabel *_lessonIntrLabel;
    ITTImageView *_teacherImageView;
    UILabel *_teacherNameLabel;
    UILabel *_teacherUnitLabel;
    UIView *_commentHeaderView;
    UILabel *_commentNumLabel;
    NSString *_commentContent;
    NSString *_commentScore;
    NSMutableArray *_data;
    NSMutableArray *_comments;
    int _page;
    NSString *_total;
    long long _likeIndex;
    UIButton *_currentButton;
    NSString *_type;
    _Bool _isVideoType;
    _Bool _isNotFirst;
    _Bool _isPlayRequest;
    HYWVideoPlayViewStatusModel *_playViewStatusModel;
    HYAnswerDataManager *_manager;
    NSString *_uuid;
    id _delegate;
    HYWCourseLearningVCModel *_learningModel;
    NSString *_courseID;
    long long _index;
    id _didGetQuizzesArrayBlock;
    NSString *_course_dept_id;
    YYLabel *_label;
    HYWCourseLearningListModel *_videoModel;
}

@property(retain, nonatomic) HYWCourseLearningListModel *videoModel; // @synthesize videoModel=_videoModel;
@property(retain, nonatomic) YYLabel *label; // @synthesize label=_label;
@property(retain, nonatomic) NSString *course_dept_id; // @synthesize course_dept_id=_course_dept_id;
@property(copy, nonatomic) id didGetQuizzesArrayBlock; // @synthesize didGetQuizzesArrayBlock=_didGetQuizzesArrayBlock;
@property(nonatomic) long long index; // @synthesize index=_index;
@property(retain, nonatomic) NSString *courseID; // @synthesize courseID=_courseID;
@property(retain, nonatomic) HYWCourseLearningVCModel *learningModel; // @synthesize learningModel=_learningModel;
@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
- (void)selectOneVideo:(long long)arg1;
- (void)currentVideoPlayFinish;
- (void)clickNextVideoButton:(long long)arg1;
- (void)insertCWPRecordUrlRequst:(id)arg1;
- (void)getVideoStatusRequst;
- (void)reloadTableRowAtIndex:(id)arg1;
- (void)changeVideoPlayStatus;
- (void)changeVideoListStatusWithIndex:(long long)arg1;
- (void)changeVideoSource:(long long)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)onWriteCommentButton:(id)arg1;
- (void)onApplyButton:(id)arg1;
- (void)intoExamVC;
- (void)exemBtnClick;
- (void)checkIsAllowQuestion;
- (void)onExemButton:(id)arg1;
- (void)onPPTButton:(id)arg1;
- (void)onCommentsButton:(id)arg1;
- (void)onVideoButton:(id)arg1;
- (void)onSelectButton:(id)arg1;
- (void)loadCourseLearningData:(id)arg1;
- (void)getCourseLearningVCRequst;
- (void)likeCommentRequstWithIndex:(long long)arg1;
- (void)addCommentRequst;
- (void)tableGetMore;
- (void)tableRefresh;
- (void)getCommentListDataWithDic:(id)arg1;
- (void)getCommentListRequst;
- (double)getMessageHeight:(id)arg1 andLabel:(id)arg2;
- (void)addSeeMoreButton;
- (void)loadLessonFooterViewData;
- (void)loadLessonHeaderViewData;
- (void)loadControllerView;
- (void)loadVideoFooterView;
- (void)loadLearningModel;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)didSecondTimeAppearBtnView;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

