//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PKBVViperModel.h"

@class NSString;

@interface PKBVUserVIPInfoModel : PKBVViperModel
{
    _Bool _vipAnnual;
    _Bool _vipValid;
    double _vipExpiredTimeSince1970;
    NSString *_vipExpiredDay;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool vipValid; // @synthesize vipValid=_vipValid;
@property(nonatomic) _Bool vipAnnual; // @synthesize vipAnnual=_vipAnnual;
@property(copy, nonatomic) NSString *vipExpiredDay; // @synthesize vipExpiredDay=_vipExpiredDay;
@property(nonatomic) double vipExpiredTimeSince1970; // @synthesize vipExpiredTimeSince1970=_vipExpiredTimeSince1970;
- (id)dictionary;
- (id)initWithDictionary:(id)arg1;
- (id)init;

@end

