//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface PKBVStatisticsUserInfo : NSObject
{
    NSString *_uid;
    NSString *_mobile;
    NSString *_email;
    NSString *_isVIP;
    NSString *_vipExpiryDate;
    NSString *_childNickname;
    NSString *_childBirthday;
    NSString *_childGender;
    NSString *_deviceCode;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *deviceCode; // @synthesize deviceCode=_deviceCode;
@property(copy, nonatomic) NSString *childGender; // @synthesize childGender=_childGender;
@property(copy, nonatomic) NSString *childBirthday; // @synthesize childBirthday=_childBirthday;
@property(copy, nonatomic) NSString *childNickname; // @synthesize childNickname=_childNickname;
@property(copy, nonatomic) NSString *vipExpiryDate; // @synthesize vipExpiryDate=_vipExpiryDate;
@property(copy, nonatomic) NSString *isVIP; // @synthesize isVIP=_isVIP;
@property(copy, nonatomic) NSString *email; // @synthesize email=_email;
@property(copy, nonatomic) NSString *mobile; // @synthesize mobile=_mobile;
@property(copy, nonatomic) NSString *uid; // @synthesize uid=_uid;
- (id)init;

@end

