//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, PKBVRecommendPageStyleModel;

@interface PKBVCommonRecommendViewNaviModel : NSObject
{
    _Bool _isVIP;
    NSString *_title;
    NSString *_scheme;
    NSString *_webViewURLString;
    unsigned long long _recommendId;
    PKBVRecommendPageStyleModel *_pageStyle;
}

- (void).cxx_destruct;
@property(retain, nonatomic) PKBVRecommendPageStyleModel *pageStyle; // @synthesize pageStyle=_pageStyle;
@property(nonatomic) _Bool isVIP; // @synthesize isVIP=_isVIP;
@property(nonatomic) unsigned long long recommendId; // @synthesize recommendId=_recommendId;
@property(copy, nonatomic) NSString *webViewURLString; // @synthesize webViewURLString=_webViewURLString;
@property(copy, nonatomic) NSString *scheme; // @synthesize scheme=_scheme;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;

@end

