//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KEPBaseJSONModel.h"

#import "KEPVideoPlayerProtocol-Protocol.h"

@class KEPVideoPlayerInfoModel, NSString;

@interface KEPKeepClassDetailModel : KEPBaseJSONModel <KEPVideoPlayerProtocol>
{
    _Bool _needPay;
    NSString *_coverUrl;
    NSString *_name;
    NSString *_kid;
    NSString *_sid;
    KEPVideoPlayerInfoModel *_videoInfo;
}

+ (_Bool)propertyIsIgnored:(id)arg1;
+ (id)keyMapper;
- (void).cxx_destruct;
@property(nonatomic) _Bool needPay; // @synthesize needPay=_needPay;
@property(retain, nonatomic) KEPVideoPlayerInfoModel *videoInfo; // @synthesize videoInfo=_videoInfo;
@property(copy, nonatomic) NSString *sid; // @synthesize sid=_sid;
@property(copy, nonatomic) NSString *kid; // @synthesize kid=_kid;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *coverUrl; // @synthesize coverUrl=_coverUrl;
@property(nonatomic) _Bool isPlus; // @dynamic isPlus;
- (id)toVideoDic;
@property(readonly, nonatomic) KEPVideoPlayerInfoModel *videoCommonInfo; // @dynamic videoCommonInfo;
@property(nonatomic) _Bool isPaied; // @dynamic isPaied;
@property(readonly, copy, nonatomic) NSString *videoSid; // @dynamic videoSid;
@property(readonly, copy, nonatomic) NSString *videoKid; // @dynamic videoKid;
@property(readonly, copy, nonatomic) NSString *videoName; // @dynamic videoName;
@property(readonly, copy, nonatomic) NSString *videoCoverUrl; // @dynamic videoCoverUrl;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

