//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KEPBaseJSONModel.h"

@class NSArray, TCExerciseChallengeEquipmentModel, TCExerciseChallengeExeciseStatsModel, TCPlusVideoModel;
@protocol KEPThumbTimelineSectionModel, TCWorkoutDynamicPioneer;

@interface TCExerciseDynamicModel : KEPBaseJSONModel
{
    _Bool _favorite;
    _Bool _hasPlus;
    _Bool _isVIP;
    _Bool _inSuit;
    unsigned long long _commentCount;
    TCExerciseChallengeExeciseStatsModel *_exerciseStats;
    NSArray<TCWorkoutDynamicPioneer> *_pioneers;
    NSArray<KEPThumbTimelineSectionModel> *_timeline;
    TCExerciseChallengeEquipmentModel *_equipment;
    TCPlusVideoModel *_videoInfo;
}

+ (id)keyMapper;
- (void).cxx_destruct;
@property(nonatomic) _Bool inSuit; // @synthesize inSuit=_inSuit;
@property(nonatomic) _Bool isVIP; // @synthesize isVIP=_isVIP;
@property(retain, nonatomic) TCPlusVideoModel *videoInfo; // @synthesize videoInfo=_videoInfo;
@property(nonatomic) _Bool hasPlus; // @synthesize hasPlus=_hasPlus;
@property(retain, nonatomic) TCExerciseChallengeEquipmentModel *equipment; // @synthesize equipment=_equipment;
@property(retain, nonatomic) NSArray<KEPThumbTimelineSectionModel> *timeline; // @synthesize timeline=_timeline;
@property(retain, nonatomic) NSArray<TCWorkoutDynamicPioneer> *pioneers; // @synthesize pioneers=_pioneers;
@property(retain, nonatomic) TCExerciseChallengeExeciseStatsModel *exerciseStats; // @synthesize exerciseStats=_exerciseStats;
@property(nonatomic) unsigned long long commentCount; // @synthesize commentCount=_commentCount;
@property(nonatomic) _Bool favorite; // @synthesize favorite=_favorite;

@end

