//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KEPBaseJSONModel.h"

#import "KEPVideoPlayerProtocol-Protocol.h"

@class KEPVideoPlayerInfoModel, NSArray, NSString;
@protocol TCPlusVideoModel;

@interface TCPlusWorkoutModel : KEPBaseJSONModel <KEPVideoPlayerProtocol>
{
    _Bool _isVip;
    _Bool _inSuit;
    NSString *_planCover;
    NSArray<TCPlusVideoModel> *_videoInfos;
    unsigned long long _local_videoIndex;
}

+ (id)keyMapper;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long local_videoIndex; // @synthesize local_videoIndex=_local_videoIndex;
@property(nonatomic) _Bool inSuit; // @synthesize inSuit=_inSuit;
@property(nonatomic) _Bool isVip; // @synthesize isVip=_isVip;
@property(retain, nonatomic) NSArray<TCPlusVideoModel> *videoInfos; // @synthesize videoInfos=_videoInfos;
@property(copy, nonatomic) NSString *planCover; // @synthesize planCover=_planCover;
@property(readonly, nonatomic) _Bool local_enablePlayPlusVideo;
- (id)local_videoWithIndex:(unsigned long long)arg1;
- (id)toVideoDic;
- (id)local_playlist;
@property(readonly, nonatomic) KEPVideoPlayerInfoModel *videoCommonInfo; // @dynamic videoCommonInfo;
@property(nonatomic) _Bool isPaied; // @dynamic isPaied;
@property(nonatomic) _Bool isPlus; // @dynamic isPlus;
@property(readonly, copy, nonatomic) NSString *videoSid; // @dynamic videoSid;
@property(readonly, copy, nonatomic) NSString *videoKid; // @dynamic videoKid;
@property(readonly, copy, nonatomic) NSString *videoName; // @dynamic videoName;
@property(readonly, copy, nonatomic) NSString *videoCoverUrl; // @dynamic videoCoverUrl;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

