//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "BUNativeAdDelegate-Protocol.h"
#import "GDTNativeAdDelegate-Protocol.h"
#import "ZYADReportProtocol-Protocol.h"

@class GDTNativeAd, NSArray, NSMutableArray, NSNumber, NSString, UIView, UIViewController, XCADVideoConfig;
@protocol XCAdSlot, XCNativeAdDataDelegate;

@interface XCNativeAdData : NSObject <BUNativeAdDelegate, GDTNativeAdDelegate, ZYADReportProtocol>
{
    _Bool _isAutoVoice;
    _Bool _handleXCAd;
    _Bool _isShowReview;
    _Bool _isShowDownLoad;
    _Bool _isShowTextLink;
    _Bool _isShowTopic;
    _Bool _isVideoAd;
    _Bool _isDownloadAppAd; 
    UIViewController *_rootViewController;
    long long _logoStyle;
    NSNumber *_voiceDelay;
    NSNumber *_cardShowDur;
    NSNumber *_buttonPopDur;
    long long _timestamps;
    id <XCNativeAdDataDelegate> _delegate;
    id _adData;
    id <XCAdSlot> _adSlot;
    NSNumber *_adId;
    XCADVideoConfig *_videoConfig;
    NSString *_adTitle;
    NSString *_adLabel;
    NSString *_adTextLinkDescription;
    NSString *_adTopicDescription;
    NSString *_adAvatarUrl;
    NSString *_adDescription;
    NSArray *_adImageList;
    UIView *_containerView;
    NSArray *_clickableViews;
    NSMutableArray *_gestersAray;
    NSString *_externalDownloadTitle;
    GDTNativeAd *_gdtNativeAd;
    NSString *_ECPMLevel;
}

@property(copy, nonatomic) NSString *ECPMLevel; // @synthesize ECPMLevel=_ECPMLevel;
@property(nonatomic) _Bool isDownloadAppAd; // @synthesize isDownloadAppAd=_isDownloadAppAd;
@property(retain, nonatomic) GDTNativeAd *gdtNativeAd; // @synthesize gdtNativeAd=_gdtNativeAd;
@property(copy, nonatomic) NSString *externalDownloadTitle; // @synthesize externalDownloadTitle=_externalDownloadTitle;
@property(retain, nonatomic) NSMutableArray *gestersAray; // @synthesize gestersAray=_gestersAray;
@property(retain, nonatomic) NSArray *clickableViews; // @synthesize clickableViews=_clickableViews;
@property(nonatomic) __weak UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) _Bool isVideoAd; // @synthesize isVideoAd=_isVideoAd;
@property(retain, nonatomic) NSArray *adImageList; // @synthesize adImageList=_adImageList;
@property(copy, nonatomic) NSString *adDescription; // @synthesize adDescription=_adDescription;
@property(copy, nonatomic) NSString *adAvatarUrl; // @synthesize adAvatarUrl=_adAvatarUrl;
@property(copy, nonatomic) NSString *adTopicDescription; // @synthesize adTopicDescription=_adTopicDescription;
@property(nonatomic) _Bool isShowTopic; // @synthesize isShowTopic=_isShowTopic;
@property(copy, nonatomic) NSString *adTextLinkDescription; // @synthesize adTextLinkDescription=_adTextLinkDescription;
@property(nonatomic) _Bool isShowTextLink; // @synthesize isShowTextLink=_isShowTextLink;
@property(nonatomic) _Bool isShowDownLoad; // @synthesize isShowDownLoad=_isShowDownLoad;
@property(nonatomic) _Bool isShowReview; // @synthesize isShowReview=_isShowReview;
@property(copy, nonatomic) NSString *adLabel; // @synthesize adLabel=_adLabel;
@property(copy, nonatomic) NSString *adTitle; // @synthesize adTitle=_adTitle;
@property(nonatomic) _Bool handleXCAd; // @synthesize handleXCAd=_handleXCAd;
@property(retain, nonatomic) XCADVideoConfig *videoConfig; // @synthesize videoConfig=_videoConfig;
@property(retain, nonatomic) NSNumber *adId; // @synthesize adId=_adId;
@property(retain, nonatomic) id <XCAdSlot> adSlot; // @synthesize adSlot=_adSlot;
@property(retain, nonatomic) id adData; // @synthesize adData=_adData;
@property(nonatomic) __weak id <XCNativeAdDataDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long timestamps; // @synthesize timestamps=_timestamps;
@property(retain, nonatomic) NSNumber *buttonPopDur; // @synthesize buttonPopDur=_buttonPopDur;
@property(retain, nonatomic) NSNumber *cardShowDur; // @synthesize cardShowDur=_cardShowDur;
@property(retain, nonatomic) NSNumber *voiceDelay; // @synthesize voiceDelay=_voiceDelay;
@property(nonatomic) _Bool isAutoVoice; // @synthesize isAutoVoice=_isAutoVoice;
@property(nonatomic) long long logoStyle; // @synthesize logoStyle=_logoStyle;
@property(nonatomic) __weak UIViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
- (void).cxx_destruct;
- (id)fetchInvokeSuccWaitTimeV2;
- (long long)fetchInvokeSuccWaitTime;
- (id)fetchInvokeSucUrls;
- (id)fetchInvokeFailUrls;
- (_Bool)fillAdDataSuccess;
- (id)adReportParmars;
- (void)nativeAdApplicationWillEnterBackground;
- (void)nativeAdClosed;
- (void)nativeAdWillPresentScreen;
- (void)nativeAdFailToLoad:(id)arg1;
- (void)nativeAdSuccessToLoad:(id)arg1;
- (void)nativeAdDidClick:(id)arg1 withView:(id)arg2;
- (void)nativeAdDidBecomeVisible:(id)arg1;
- (void)nativeAdDidExposure;
- (void)nativeAdBecomeDisVisible;
- (void)clickAdAtView:(id)arg1;
- (void)nativeAdBecomeVisible;
- (void)clickable:(id)arg1;
- (void)nativeAdDidSelectDisgustWithReasons:(id)arg1;
- (void)cleanContainner;
- (void)unregisterView;
- (void)registerContainer:(id)arg1 withClickableViews:(id)arg2 listView:(id)arg3;
- (id)getECPMLevel;
- (id)adIconName;
- (_Bool)isEqualToNativeAdData:(id)arg1;
- (_Bool)isMoreMedias;
- (id)externalIconUrl;
- (void)updateNativeAdDataWithBaiduAdData:(id)arg1;
- (void)updateNativeAdDataWithJHNativeAdData:(id)arg1;
- (void)updateNativeAdDataWithCusNativeAdData:(id)arg1;
- (void)updateNativeAdDataWithGdtNativeAdData:(id)arg1;
- (void)updateNativeAdDataWithGdtUnifiedData:(id)arg1;
- (void)updateNativeAdDataWithBuAdData:(id)arg1;
- (void)updateNativeAdV2DataWithCusNativeAdData:(id)arg1;
- (void)updateNativeAdData;
- (id)initWithAdData:(id)arg1 adSource:(id)arg2;
- (id)adDataJson;
- (id)checkImageUrl;
@property(nonatomic) _Bool didShowed;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

