//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSAttributedString, NSString, UIColor, XCNativeAdData;

@interface XCNativeAdViewModel : NSObject
{
    UIColor *_adLogoBackgroudColor;
    double _adLogoBgRadius;
    NSAttributedString *_adLogoAttribute;
    NSArray *_imageFrams;
    NSAttributedString *_adTitleAttribute;
    NSAttributedString *_adDescriptionAttribute;
    XCNativeAdData *_adData;
    NSAttributedString *_adExtralButtonTitle;
    double _viewHeight;
    NSString *_reportSource;
    long long _style;
    struct CGRect _adLogoFrame;
    struct CGRect _avatarFrame;
    struct CGRect _adTitleFrame;
    struct CGRect _adDescriptionFrame;
    struct CGRect _separatorLineFrame;
    struct CGRect _bottomViewFrame;
    struct CGRect _textLinkFrame;
    struct CGRect _topicFrame;
}

+ (id)nativeAdViewModelWithNativeAdData:(id)arg1 nativeAdConfig:(id)arg2;
+ (id)nativeAdViewModelWithNativeAdData:(id)arg1 nativeAdStyle:(long long)arg2;
@property(nonatomic) struct CGRect topicFrame; // @synthesize topicFrame=_topicFrame;
@property(nonatomic) struct CGRect textLinkFrame; // @synthesize textLinkFrame=_textLinkFrame;
@property(nonatomic) long long style; // @synthesize style=_style;
@property(retain, nonatomic) NSString *reportSource; // @synthesize reportSource=_reportSource;
@property(nonatomic) double viewHeight; // @synthesize viewHeight=_viewHeight;
@property(nonatomic) struct CGRect bottomViewFrame; // @synthesize bottomViewFrame=_bottomViewFrame;
@property(nonatomic) struct CGRect separatorLineFrame; // @synthesize separatorLineFrame=_separatorLineFrame;
@property(retain, nonatomic) NSAttributedString *adExtralButtonTitle; // @synthesize adExtralButtonTitle=_adExtralButtonTitle;
@property(readonly, nonatomic) XCNativeAdData *adData; // @synthesize adData=_adData;
@property(retain, nonatomic) NSAttributedString *adDescriptionAttribute; // @synthesize adDescriptionAttribute=_adDescriptionAttribute;
@property(retain, nonatomic) NSAttributedString *adTitleAttribute; // @synthesize adTitleAttribute=_adTitleAttribute;
@property(retain, nonatomic) NSArray *imageFrams; // @synthesize imageFrams=_imageFrams;
@property(nonatomic) struct CGRect adDescriptionFrame; // @synthesize adDescriptionFrame=_adDescriptionFrame;
@property(nonatomic) struct CGRect adTitleFrame; // @synthesize adTitleFrame=_adTitleFrame;
@property(nonatomic) struct CGRect avatarFrame; // @synthesize avatarFrame=_avatarFrame;
@property(retain, nonatomic) NSAttributedString *adLogoAttribute; // @synthesize adLogoAttribute=_adLogoAttribute;
@property(nonatomic) double adLogoBgRadius; // @synthesize adLogoBgRadius=_adLogoBgRadius;
@property(nonatomic) struct CGRect adLogoFrame; // @synthesize adLogoFrame=_adLogoFrame;
@property(retain, nonatomic) UIColor *adLogoBackgroudColor; // @synthesize adLogoBackgroudColor=_adLogoBackgroudColor;
- (void).cxx_destruct;

@end

