//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>


@class CALayer, NSString, UIButton, UIView, XCAdInfo, XCNativeAdView, ZYAdInfoCellBottomView, ZYAdInfoFlow, ZYButton, ZYUICellBottomToolBar;

@interface ZYNativeAdV2TableViewCell : UITableViewCell
{
    XCNativeAdView *_feedAdView;
    ZYAdInfoFlow *_infoFlow;
    UIView *_listView;
    CALayer *_lineLayer;
    ZYUICellBottomToolBar *_bottomToolBar;
    ZYAdInfoCellBottomView *_infoBottomView;
    UIButton *_textLinkButton;
    ZYButton *_topicButton;
    XCAdInfo *_nativeAd;
}

@property(retain, nonatomic) XCAdInfo *nativeAd; // @synthesize nativeAd=_nativeAd;
@property(retain, nonatomic) ZYButton *topicButton; // @synthesize topicButton=_topicButton;
@property(retain, nonatomic) UIButton *textLinkButton; // @synthesize textLinkButton=_textLinkButton;
@property(retain, nonatomic) ZYAdInfoCellBottomView *infoBottomView; // @synthesize infoBottomView=_infoBottomView;
@property(retain, nonatomic) ZYUICellBottomToolBar *bottomToolBar; // @synthesize bottomToolBar=_bottomToolBar;
@property(retain, nonatomic) CALayer *lineLayer; // @synthesize lineLayer=_lineLayer;
@property(nonatomic) __weak UIView *listView; // @synthesize listView=_listView;
@property(retain, nonatomic) ZYAdInfoFlow *infoFlow; // @synthesize infoFlow=_infoFlow;
@property(retain, nonatomic) XCNativeAdView *feedAdView; // @synthesize feedAdView=_feedAdView;
- (id)currentReportSource;
- (id)postWithAdInfo:(id)arg1;
- (id)viewModelWithAdInfo:(id)arg1;
- (void)reportDisgustWithReasons:(id)arg1;
- (void)nativeAdViewDidClickDeleteAd:(id)arg1;
- (void)upDownViewUnLikeClick:(id)arg1;
- (void)upDownViewLikeClick:(id)arg1;
- (void)upDownViewLikedUserClick:(id)arg1;
- (void)cancelPickerView:(id)arg1;
- (void)snsOperationView:(id)arg1 didSelectedPlatform:(id)arg2;
- (void)operationCopyLinkOperationView:(id)arg1;
- (void)commentClick;
- (void)shareClick;
- (void)night_updateColor;
- (id)textLinkAttributeWithString:(id)arg1 textColor:(id)arg2 image:(id)arg3;
- (void)bindADInfo:(id)arg1 listView:(id)arg2;
- (void)updateNotification:(id)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

