//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ZYUIRecommendBaseTableViewCell.h"

#import "ZYOperationViewDelegate-Protocol.h"
#import "ZYUIPostAmazingCommentViewDelegate-Protocol.h"
#import "ZYUIPostsRewardViewDelegate-Protocol.h"
#import "ZYUIUpDownViewDelegate-Protocol.h"
#import "ZYUIVoteViewDelegate-Protocol.h"

@class NSString, NSURL, UIButton, UIImageView, UIView, ZYButton, ZYDiscussionLabelView, ZYLabel, ZYOriginalProtectedView, ZYPostAttitudeCountView, ZYPostExcellentTopicView, ZYPostHotInTopicSectionView, ZYPostLocationView, ZYPostMoreHotInTopicView, ZYPostRankingView, ZYUIPostCellInterestView, ZYUIPostsCommentView, ZYUIPostsRewardView, ZYUIVoteView, ZYView;

@interface ZYUIPostsTableViewCell : ZYUIRecommendBaseTableViewCell <ZYUIPostAmazingCommentViewDelegate, ZYUIVoteViewDelegate, ZYUIUpDownViewDelegate, ZYOperationViewDelegate, ZYUIPostsRewardViewDelegate>
{
    _Bool _canAutoPlay;
    UIView *_autoPlayView;
    ZYView *_wyMusicView;
    UIImageView *_wyMusicPic;
    ZYLabel *_wyMusicTitle;
    ZYLabel *_wyMusicAuthor;
    ZYView *_weChatView;
    UIImageView *_weChatPic;
    ZYView *_linkBackGroundView;
    ZYLabel *_linkLabel;
    UIImageView *_linkImageView;
    UIImageView *_linkLogoView;
    ZYUIVoteView *_voteView;
    double _postTitleHeight;
    double _titleLabelWidth;
    UIButton *_activityButton;
    ZYPostAttitudeCountView *_listAttitudeView;
    ZYButton *_copyrightJointButton;
    long long _sourceType;
    NSURL *_jumpAppLink;
    NSString *_jumpWebLink;
    NSURL *_copyrightLink;
    UIImageView *_cornerRadiusMaskImageView;
    ZYOriginalProtectedView *_originalProtectedView;
    ZYDiscussionLabelView *_discussionView;
    ZYUIPostsCommentView *_topicCommentView;
    ZYPostExcellentTopicView *_excellentTopicView;
    ZYPostLocationView *_locationView;
    ZYPostHotInTopicSectionView *_hotInTopicSectionView;
    ZYPostMoreHotInTopicView *_moreHotInTopicView;
    ZYPostRankingView *_rankingView;
    ZYUIPostsRewardView *_rewardView;
    ZYLabel *_adLabel;
    ZYUIPostCellInterestView *_interestView;
}

+ (double)activityViewHeight;
+ (double)linkViewHeight;
+ (double)musicViewHeight;
+ (double)cellHeightWithPost:(id)arg1 helper:(id)arg2 showComment:(_Bool)arg3 isDetail:(_Bool)arg4 showTime:(_Bool)arg5;
@property(retain, nonatomic) ZYUIPostCellInterestView *interestView; // @synthesize interestView=_interestView;
@property(retain, nonatomic) ZYLabel *adLabel; // @synthesize adLabel=_adLabel;
@property(retain, nonatomic) ZYUIPostsRewardView *rewardView; // @synthesize rewardView=_rewardView;
@property(retain, nonatomic) ZYPostRankingView *rankingView; // @synthesize rankingView=_rankingView;
@property(retain, nonatomic) ZYPostMoreHotInTopicView *moreHotInTopicView; // @synthesize moreHotInTopicView=_moreHotInTopicView;
@property(retain, nonatomic) ZYPostHotInTopicSectionView *hotInTopicSectionView; // @synthesize hotInTopicSectionView=_hotInTopicSectionView;
@property(retain, nonatomic) ZYPostLocationView *locationView; // @synthesize locationView=_locationView;
@property(retain, nonatomic) ZYPostExcellentTopicView *excellentTopicView; // @synthesize excellentTopicView=_excellentTopicView;
@property(retain, nonatomic) ZYUIPostsCommentView *topicCommentView; // @synthesize topicCommentView=_topicCommentView;
@property(retain, nonatomic) ZYDiscussionLabelView *discussionView; // @synthesize discussionView=_discussionView;
@property(retain, nonatomic) ZYOriginalProtectedView *originalProtectedView; // @synthesize originalProtectedView=_originalProtectedView;
@property(retain, nonatomic) UIImageView *cornerRadiusMaskImageView; // @synthesize cornerRadiusMaskImageView=_cornerRadiusMaskImageView;
@property(retain, nonatomic) NSURL *copyrightLink; // @synthesize copyrightLink=_copyrightLink;
@property(copy, nonatomic) NSString *jumpWebLink; // @synthesize jumpWebLink=_jumpWebLink;
@property(retain, nonatomic) NSURL *jumpAppLink; // @synthesize jumpAppLink=_jumpAppLink;
@property(nonatomic) long long sourceType; // @synthesize sourceType=_sourceType;
@property(retain, nonatomic) ZYButton *copyrightJointButton; // @synthesize copyrightJointButton=_copyrightJointButton;
@property(retain, nonatomic) ZYPostAttitudeCountView *listAttitudeView; // @synthesize listAttitudeView=_listAttitudeView;
@property(retain, nonatomic) UIButton *activityButton; // @synthesize activityButton=_activityButton;
@property(nonatomic) double titleLabelWidth; // @synthesize titleLabelWidth=_titleLabelWidth;
@property(nonatomic) double postTitleHeight; // @synthesize postTitleHeight=_postTitleHeight;
@property(retain, nonatomic) ZYUIVoteView *voteView; // @synthesize voteView=_voteView;
@property(retain, nonatomic) UIImageView *linkLogoView; // @synthesize linkLogoView=_linkLogoView;
@property(retain, nonatomic) UIImageView *linkImageView; // @synthesize linkImageView=_linkImageView;
@property(retain, nonatomic) ZYLabel *linkLabel; // @synthesize linkLabel=_linkLabel;
@property(retain, nonatomic) ZYView *linkBackGroundView; // @synthesize linkBackGroundView=_linkBackGroundView;
@property(retain, nonatomic) UIImageView *weChatPic; // @synthesize weChatPic=_weChatPic;
@property(retain, nonatomic) ZYView *weChatView; // @synthesize weChatView=_weChatView;
@property(retain, nonatomic) ZYLabel *wyMusicAuthor; // @synthesize wyMusicAuthor=_wyMusicAuthor;
@property(retain, nonatomic) ZYLabel *wyMusicTitle; // @synthesize wyMusicTitle=_wyMusicTitle;
@property(retain, nonatomic) UIImageView *wyMusicPic; // @synthesize wyMusicPic=_wyMusicPic;
@property(retain, nonatomic) ZYView *wyMusicView; // @synthesize wyMusicView=_wyMusicView;
@property(retain, nonatomic) UIView *autoPlayView; // @synthesize autoPlayView=_autoPlayView;
@property(nonatomic) _Bool canAutoPlay; // @synthesize canAutoPlay=_canAutoPlay;
- (void).cxx_destruct;
- (void)setTopicDetail:(id)arg1;
- (void)clickWhatIsRewardAction;
- (void)clickRewardAction;
- (void)clickShowHotDiscussDetail;
- (void)clickForMoreHots;
- (void)topicCommentClick;
- (void)cellDidEndDisplay;
- (void)cellWillDisplay;
- (void)reportBrandPShow;
- (void)reportWikiViewPoint;
- (void)anonymityLikeClick;
- (void)anonymityChatClick;
- (void)linkAction:(_Bool)arg1;
- (void)mediaDidTapWithMediaIsVideo:(_Bool)arg1;
- (void)linkAction;
- (id)currentPostUserId;
- (id)currentPostId;
- (id)currentPostTopicId;
- (long long)currentPostType;
- (long long)currentPostPartId;
- (void)clickImgAction:(id)arg1;
- (void)jumpToAnotherSource;
- (void)updateAttitudeDes:(id)arg1;
- (void)toEpauletUrl;
- (double)configLinkWithCurrentY:(double)arg1;
- (double)configLinkWithModel:(id)arg1;
- (void)voteWithVoteItemId:(id)arg1;
- (void)voteViewClicked;
- (void)showFollowStatusIfNeed;
- (void)setTitleLabel;
- (void)clickCommentTool;
- (void)setShowExcellentAfterTime:(_Bool)arg1;
- (void)showMasterNameAfterCreateTime;
- (void)setShowPostCreateTime:(_Bool)arg1;
- (void)bindWithViewModel:(id)arg1 dataSource:(id)arg2 helper:(id)arg3 indexPath:(id)arg4;
- (double)setExcellentTopicStyleWith:(double)arg1;
- (double)setNormarlTopicStyleWith:(double)arg1;
- (void)setAccountRoles;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

