//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol iBBUserModuleDispatchProtocol;

@interface BBMTarget_UserCenter : NSObject
{
    id <iBBUserModuleDispatchProtocol> _channel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) id <iBBUserModuleDispatchProtocol> channel; // @synthesize channel=_channel;
- (id)bbmAction_updateUserInfo:(id)arg1;
- (void)bbmAction_removeMonitorLogOut:(id)arg1;
- (void)bbmAction_monitorLogOut:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)bbmAction_removeAllMonitor;
- (void)bbmAction_removeMonitorFirstLoginStatus:(id)arg1;
- (void)bbmAction_monitorFirstLoginStatus:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)bbmAction_removeMonitorLoginChange:(id)arg1;
- (void)bbmAction_monitorLoginChange:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)bbmAction_loginAuto:(CDUnknownBlockType)arg1;
- (void)bbmAction_logout:(CDUnknownBlockType)arg1;
- (void)bbmAction_loginRefresh:(CDUnknownBlockType)arg1;
- (_Bool)bbmAction_isNeedRefreshADWithCurrentUserOnline:(_Bool)arg1 isVIP:(_Bool)arg2;
- (id)bbmAction_getToolBarActivityPageWithViewController:(id)arg1 entrance:(id)arg2 url:(id)arg3 title:(id)arg4 toolbarHeight:(double)arg5;
- (id)bbmAction_getActivityPageWithViewController:(id)arg1 entrance:(id)arg2 url:(id)arg3 title:(id)arg4;
- (void)bbmAction_openActivityPageWithPresentedVC:(id)arg1 entrance:(id)arg2 url:(id)arg3 title:(id)arg4 dismissBlock:(CDUnknownBlockType)arg5;
- (void)bbmAction_openActivityPageWithViewController:(id)arg1 entrance:(id)arg2 url:(id)arg3 title:(id)arg4;
- (void)bbmAction_openBabyInfoViewControllerWithDismissBlock:(CDUnknownBlockType)arg1;
- (void)bbmAction_openCoursePayViewControllerWithParams:(id)arg1 payResultBlock:(CDUnknownBlockType)arg2;
- (void)bbmAction_openCoursePayViewControllerWithPackageId:(long long)arg1 entrance:(id)arg2 payResultBlock:(CDUnknownBlockType)arg3;
- (void)bbmAction_clearCourseUserInfo;
- (id)bbmAction_courseUserInfo;
- (void)bbmAction_getUserInfoWithCompleteBlock:(CDUnknownBlockType)arg1;
- (void)bbmAction_updateUserInfoWithUserModel:(id)arg1 completeBlock:(CDUnknownBlockType)arg2;
- (void)bbmAction_nrAppstorePayWithViewController:(id)arg1 entrance:(id)arg2 packageId:(id)arg3;
- (void)bbmAction_gsBuyVipPackage:(id)arg1 channel:(id)arg2 entrance:(id)arg3 viewController:(id)arg4;
- (void)bbmAction_qqBuyVipPackage:(id)arg1 channel:(id)arg2 entrance:(id)arg3 viewController:(id)arg4;
- (void)bbmAction_brBuyVipPackage:(id)arg1 channel:(id)arg2 entrance:(id)arg3 viewController:(id)arg4;
- (void)bbmAction_nrBuyVipPackage:(id)arg1 channel:(id)arg2 entrance:(id)arg3 viewController:(id)arg4;
- (void)bbmAction_loginAccountActionWithViewController:(id)arg1 dismissBlock:(CDUnknownBlockType)arg2;
- (void)bbmAction_loginAccountActionWithViewController:(id)arg1;
- (void)bbmAction_bindAccountActionWithViewController:(id)arg1 dismissBlock:(CDUnknownBlockType)arg2;
- (void)bbmAction_bindAccountActionWithViewController:(id)arg1;
- (void)bbmAction_registeredActionWithViewController:(id)arg1 dismissBlock:(CDUnknownBlockType)arg2;
- (void)bbmAction_registeredActionWithViewController:(id)arg1;
- (void)bbmAction_vipPackageInfoDataWithCompleteBlock:(CDUnknownBlockType)arg1;
- (id)bbmAction_registeredAndBindViewControllerWithEntrance:(id)arg1 dismissBlock:(CDUnknownBlockType)arg2;
- (id)bbmAction_registeredAndBindViewControllerWithEntrance:(id)arg1;
- (id)bbmAction_registeredAndBindViewController;
- (id)bbmAction_bindViewControllerWithEntrance:(id)arg1 dismissBlock:(CDUnknownBlockType)arg2;
- (id)bbmAction_bindViewControllerWithEntrance:(id)arg1;
- (id)bbmAction_bindViewController;
- (void)bbmAction_registerFunnelAnalysisWithEntrance:(id)arg1;
- (id)bbmAction_babyInfoViewControllerWithEntrance:(id)arg1 showSkip:(_Bool)arg2 willDismissBlock:(CDUnknownBlockType)arg3;
- (id)bbmAction_babyInfoViewControllerWithEntrance:(id)arg1 willDismissBlock:(CDUnknownBlockType)arg2;
- (id)bbmAction_vipViewControllerWillDismissBlock:(CDUnknownBlockType)arg1 appStoreProductID:(id)arg2 entrance:(id)arg3;
- (void)bbmAction_openUserViewController:(id)arg1 isPresent:(_Bool)arg2 navigationControllerBlock:(CDUnknownBlockType)arg3 packageId:(long long)arg4 dismissBlock:(CDUnknownBlockType)arg5;
- (id)bbmAction_userViewController;
- (void)bbmAction_loginWithCaller:(id)arg1 launchOnPresent:(_Bool)arg2 entrance:(id)arg3 navBlock:(CDUnknownBlockType)arg4 willDismissBlock:(CDUnknownBlockType)arg5 completeBlock:(CDUnknownBlockType)arg6;
- (id)bbmAction_loginViewControllerWithEntrance:(id)arg1 dismissBlock:(CDUnknownBlockType)arg2;
- (id)bbmAction_mineUserHeaderView:(id)arg1;
- (id)bbmAction_userHeaderView:(id)arg1;
- (long long)bbmAction_productVipExpiryDate;
- (long long)bbmAction_baseVipExpiryDate;
- (long long)bbmAction_registerDate;
- (id)bbmAction_mobilePhone;
- (long long)bbmAction_accountID;
- (_Bool)bbmAction_isNeedBindAccount;
- (_Bool)bbmAction_userHasPayNRVip;
- (long long)bbmAction_appRegisterDate;
- (_Bool)bbmAction_userHasHDRights;
- (_Bool)bbmAction_userIsBaseVip;
- (_Bool)bbmAction_userIsNRVip;
- (_Bool)bbmAction_userIsAccount;
- (_Bool)bbmAction_userIsVIP;
- (_Bool)bbmAction_userIsOnLine;
- (void)dealloc;
- (id)init;
- (void)bbmAction_loginWithCaller:(id)arg1 launchOnPresent:(_Bool)arg2 entrance:(id)arg3 completeBlock:(CDUnknownBlockType)arg4;
- (void)bbmAction_loginWithCaller:(id)arg1 launchOnPresent:(_Bool)arg2 entrance:(id)arg3 willDismissBlock:(CDUnknownBlockType)arg4;
- (void)bbmAction_loginWithCaller:(id)arg1 launchOnPresent:(_Bool)arg2 entrance:(id)arg3 navBlock:(CDUnknownBlockType)arg4;
- (void)bbmAction_loginWithCaller:(id)arg1 launchOnPresent:(_Bool)arg2 entrance:(id)arg3;
- (id)bbmAction_loginViewControllerWithEntrance:(id)arg1;
- (id)bbmAction_loginViewControllerWillDismissBlock:(CDUnknownBlockType)arg1;
- (id)bbmAction_loginViewController;
- (void)bbmAction_openVipMemberFeedbackVC;

@end

