//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface BRAppManager : NSObject
{
}

+ (void)eventStatisticsWithOperation:(id)arg1;
+ (id)analysis;
+ (id)vipGuideModelAtType:(long long)arg1;
+ (void)openVIPPage:(_Bool)arg1;
+ (void)authorizesWithType:(long long)arg1 isVIP:(_Bool)arg2 passBlock:(CDUnknownBlockType)arg3;
+ (void)registerCommonUI;

@end

