//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString, UITextView;

@interface NRPlayControlManager : NSObject
{
    _Bool _allowUseWWANForPlay;
    _Bool _allowUseWWANForDownload;
    _Bool _finishMonitor;
    _Bool _isVideoControllerPresented;
    _Bool _adjustDistance;
    _Bool _isFirstNet;
    _Bool _reachableViaWWAN;
    _Bool _reachableViaWiFi;
    _Bool _fristDownloadFinish;
    long long _lastCloseBreakType;
    NSString *_needDelayNotificationName;
    NSString *_lastCloseBreakTime;
    double _lastCloseBreakTimeInterval;
    UITextView *_logLabel;
    NSMutableArray *_downloadAlertRecords;
    NSMutableArray *_downloadToastRecords;
    NSMutableArray *_didShowedMsgArray;
    NSMutableArray *_logArray;
    double _enterBackgroundTime;
}

+ (void)addLog:(id)arg1;
+ (id)shareInstance;
+ (id)columnNameBy:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) double enterBackgroundTime; // @synthesize enterBackgroundTime=_enterBackgroundTime;
@property(retain, nonatomic) NSMutableArray *logArray; // @synthesize logArray=_logArray;
@property(nonatomic) _Bool fristDownloadFinish; // @synthesize fristDownloadFinish=_fristDownloadFinish;
@property(retain, nonatomic) NSMutableArray *didShowedMsgArray; // @synthesize didShowedMsgArray=_didShowedMsgArray;
@property(retain, nonatomic) NSMutableArray *downloadToastRecords; // @synthesize downloadToastRecords=_downloadToastRecords;
@property(retain, nonatomic) NSMutableArray *downloadAlertRecords; // @synthesize downloadAlertRecords=_downloadAlertRecords;
@property(retain, nonatomic) UITextView *logLabel; // @synthesize logLabel=_logLabel;
@property(nonatomic) _Bool reachableViaWiFi; // @synthesize reachableViaWiFi=_reachableViaWiFi;
@property(nonatomic) _Bool reachableViaWWAN; // @synthesize reachableViaWWAN=_reachableViaWWAN;
@property(nonatomic) _Bool isFirstNet; // @synthesize isFirstNet=_isFirstNet;
@property(nonatomic) double lastCloseBreakTimeInterval; // @synthesize lastCloseBreakTimeInterval=_lastCloseBreakTimeInterval;
@property(copy, nonatomic) NSString *lastCloseBreakTime; // @synthesize lastCloseBreakTime=_lastCloseBreakTime;
@property(nonatomic) _Bool adjustDistance; // @synthesize adjustDistance=_adjustDistance;
@property(nonatomic) _Bool isVideoControllerPresented; // @synthesize isVideoControllerPresented=_isVideoControllerPresented;
@property(nonatomic) _Bool finishMonitor; // @synthesize finishMonitor=_finishMonitor;
@property(retain, nonatomic) NSString *needDelayNotificationName; // @synthesize needDelayNotificationName=_needDelayNotificationName;
@property(nonatomic) _Bool allowUseWWANForDownload; // @synthesize allowUseWWANForDownload=_allowUseWWANForDownload;
@property(nonatomic) _Bool allowUseWWANForPlay; // @synthesize allowUseWWANForPlay=_allowUseWWANForPlay;
@property(nonatomic) long long lastCloseBreakType; // @synthesize lastCloseBreakType=_lastCloseBreakType;
- (void)startM3U8DownloadTask;
- (void)pauseAllM3U8DownloadTask;
- (void)pauseAllDownloadTask;
- (void)resumeAllM3U8DownloadTask;
- (void)resumeAllDownloadTask;
- (void)appendLog:(id)arg1;
- (_Bool)isRestAtNoon;
- (_Bool)isRestAtNight;
- (void)networkStatusIsChange:(id)arg1;
- (id)getCurrentDate:(id)arg1;
- (void)showDownloadTipNoRepeat:(id)arg1;
- (void)clearAllowUseWWANForDownload;
- (void)clearDownloadToastRecord:(Class)arg1;
- (_Bool)needShowDownloadToast:(Class)arg1;
- (void)clearDownloadAlertRecord;
- (_Bool)needShowDownloadAlert:(Class)arg1;
- (_Bool)needShowNetworkWarmingForDownload;
- (_Bool)needShowNetworkWarming;
- (_Bool)isRest_4miniApp;
- (void)clearLastCloseBreakType:(long long)arg1;
- (_Bool)isForbid;
- (void)IncrementPlayTime;
- (void)InitializePlayTime;
- (long long)breakType;
- (_Bool)isPlayingAtBackGround;
- (void)finishSingleUse;
- (void)finishSingleUseIfNeed;
- (_Bool)reachFinishSingleUseTime;
- (_Bool)isNewSingleUse;
- (void)dealloc;
- (void)initNetworkReachability;
- (void)addNetworkStatusObserver;
- (id)init;
- (void)uploadAudioDownloadRecord;
- (void)uploadAudioPlayRecord;
- (void)uploadTotalAudioPlayTime;
- (void)uploadTotalVideoPlayTime;
- (void)uploadDownloadRecord;
- (void)uploadPlayRecord;

@end

