//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKit.h>

@class NSArray, NSString, SEUserVipInfoModel;

@interface SEUserModel : NSObject
{
    _Bool _isOnline;
    _Bool _isUserLogout;
    _Bool _isStartVip;
    _Bool _isGuestCreateAccount;
    _Bool _isNeedJudgeLogout;
    _Bool _supportCoin;
    NSString *_phone;
    NSString *_nickName;
    NSString *_avatarUrl;
    NSString *_avatarImage;
    NSString *_stateDescUnlogin;
    NSArray *_vipTypeList;
    SEUserVipInfoModel *_bbVipInfoModel;
    SEUserVipInfoModel *_nrVipInfoModel;
    long long _accountID;
    NSString *_accountIDSignature;
    NSString *_loginCode;
    long long _loginStamp;
    NSString *_loginSignature;
    NSString *_vipSignature;
    long long _vipEndTime;
    long long _vipType2;
    long long _vipExpiry;
    long long _vipStartTime;
    NSString *_syncSignature;
    NSString *_vipRightsID;
    long long _registerDate;
    long long _appRegisterDate;
    NSString *_account;
    long long _isPassword;
    long long _isRegister;
    NSString *_accountIDCode;
    NSString *_sign;
    NSString *_userName;
    long long _birthday;
    NSString *_location;
    long long _sex;
    NSString *_ip;
    NSString *_coverUrl;
    long long _provinceID;
    NSString *_email;
    long long _isPayPassword;
    long long _countryID;
    long long _cityID;
    long long _districtID;
    long long _userAccountType;
    NSString *_bindPhone;
    NSString *_unionID;
    NSString *_userCode;
}

+ (id)stateDescUnlogin:(_Bool)arg1;
+ (_Bool)loginState;
+ (void)updateLoginState:(_Bool)arg1;
+ (id)accountLoginInfo;
+ (void)accountLogot;
+ (id)lastLoginUserModel;
+ (id)cacheLoginUserModel;
+ (id)persistentProperties;
+ (id)primaryKey;
+ (id)tableName;
+ (id)dbName;
+ (id)modelContainerPropertyGenericClass;
+ (id)modelCustomPropertyMapper;

@property(nonatomic) _Bool supportCoin; // @synthesize supportCoin=_supportCoin;
@property(retain, nonatomic) NSString *userCode; // @synthesize userCode=_userCode;
@property(retain, nonatomic) NSString *unionID; // @synthesize unionID=_unionID;
@property(nonatomic) _Bool isNeedJudgeLogout; // @synthesize isNeedJudgeLogout=_isNeedJudgeLogout;
@property(retain, nonatomic) NSString *bindPhone; // @synthesize bindPhone=_bindPhone;
@property(nonatomic) long long userAccountType; // @synthesize userAccountType=_userAccountType;
@property(nonatomic) _Bool isGuestCreateAccount; // @synthesize isGuestCreateAccount=_isGuestCreateAccount;
@property(nonatomic) long long districtID; // @synthesize districtID=_districtID;
@property(nonatomic) long long cityID; // @synthesize cityID=_cityID;
@property(nonatomic) long long countryID; // @synthesize countryID=_countryID;
@property(nonatomic) long long isPayPassword; // @synthesize isPayPassword=_isPayPassword;
@property(copy, nonatomic) NSString *email; // @synthesize email=_email;
@property(nonatomic) long long provinceID; // @synthesize provinceID=_provinceID;
@property(copy, nonatomic) NSString *coverUrl; // @synthesize coverUrl=_coverUrl;
@property(copy, nonatomic) NSString *ip; // @synthesize ip=_ip;
@property(nonatomic) long long sex; // @synthesize sex=_sex;
@property(copy, nonatomic) NSString *location; // @synthesize location=_location;
@property(nonatomic) long long birthday; // @synthesize birthday=_birthday;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(copy, nonatomic) NSString *sign; // @synthesize sign=_sign;
@property(copy, nonatomic) NSString *accountIDCode; // @synthesize accountIDCode=_accountIDCode;
@property(nonatomic) long long isRegister; // @synthesize isRegister=_isRegister;
@property(nonatomic) long long isPassword; // @synthesize isPassword=_isPassword;
@property(copy, nonatomic) NSString *account; // @synthesize account=_account;
@property(nonatomic) long long appRegisterDate; // @synthesize appRegisterDate=_appRegisterDate;
@property(nonatomic) long long registerDate; // @synthesize registerDate=_registerDate;
@property(copy, nonatomic) NSString *vipRightsID; // @synthesize vipRightsID=_vipRightsID;
@property(copy, nonatomic) NSString *syncSignature; // @synthesize syncSignature=_syncSignature;
@property(nonatomic) long long vipStartTime; // @synthesize vipStartTime=_vipStartTime;
@property(nonatomic) long long vipExpiry; // @synthesize vipExpiry=_vipExpiry;
@property(nonatomic) long long vipType2; // @synthesize vipType2=_vipType2;
@property(nonatomic) long long vipEndTime; // @synthesize vipEndTime=_vipEndTime;
@property(copy, nonatomic) NSString *vipSignature; // @synthesize vipSignature=_vipSignature;
@property(copy, nonatomic) NSString *loginSignature; // @synthesize loginSignature=_loginSignature;
@property(nonatomic) long long loginStamp; // @synthesize loginStamp=_loginStamp;
@property(copy, nonatomic) NSString *loginCode; // @synthesize loginCode=_loginCode;
@property(copy, nonatomic) NSString *accountIDSignature; // @synthesize accountIDSignature=_accountIDSignature;
@property(nonatomic) long long accountID; // @synthesize accountID=_accountID;
@property(copy, nonatomic) SEUserVipInfoModel *nrVipInfoModel; // @synthesize nrVipInfoModel=_nrVipInfoModel;
@property(copy, nonatomic) SEUserVipInfoModel *bbVipInfoModel; // @synthesize bbVipInfoModel=_bbVipInfoModel;
@property(copy, nonatomic) NSArray *vipTypeList; // @synthesize vipTypeList=_vipTypeList;
@property(copy, nonatomic) NSString *stateDescUnlogin; // @synthesize stateDescUnlogin=_stateDescUnlogin;
@property(nonatomic) _Bool isStartVip; // @synthesize isStartVip=_isStartVip;
@property(nonatomic) _Bool isUserLogout; // @synthesize isUserLogout=_isUserLogout;
@property(copy, nonatomic) NSString *avatarImage; // @synthesize avatarImage=_avatarImage;
@property(copy, nonatomic) NSString *avatarUrl; // @synthesize avatarUrl=_avatarUrl;
@property(copy, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
@property(copy, nonatomic) NSString *phone; // @synthesize phone=_phone;
@property(nonatomic) _Bool isOnline; // @synthesize isOnline=_isOnline;
- (id)guestNickname;
- (_Bool)isSongSuperVip;
- (id)productVipInfoModel;
- (id)qqVipInfoModel;
- (id)songSuperVipInfoModel;
- (id)babybusVipInfoModel;
- (id)vipInfoModelWithType:(int)arg1;
- (void)test4ExpiredGuest:(id)arg1;
- (_Bool)isVipExpiredGuest:(id)arg1;
- (void)autoLogoutGuestIfNeed:(id)arg1;
- (_Bool)isShowGuestLogoutState;
- (_Bool)isSupportGuestAccountOnlyExist;
- (_Bool)isGuestPurchasedSuccessfully;
- (_Bool)isNeedBindAccount;
- (_Bool)isGuestAccount;
- (_Bool)isCreateGuestAccount;
- (void)bindPhoneSucc;
- (void)updateBindAccountType;
@property(readonly, nonatomic) long long baseVipType;
@property(readonly, nonatomic) long long vipType;
@property(readonly, nonatomic) NSString *vipStateDesc;
- (_Bool)neverLoginMoreThanOneMonth;
- (_Bool)loginState;
- (void)updateOnLine;
- (void)updateLoginState:(_Bool)arg1;
- (void)saveUserInfo;
- (void)accountLogot;
- (void)save;
- (_Bool)isEqual:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

