//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSBundle, NSCache, NSString;

@interface CYCacheManager : NSObject
{
    _Bool _forbiddenMapGesture;
    _Bool _isAPPReview;
    _Bool _isShowInvite;
    _Bool _testTyphoon;
    _Bool _testInsertAd;
    _Bool _isFirstLaunch;
    _Bool _closeTyphoonCard;
    NSCache *_cache;
    NSString *_selectedAPPLanuage;
    NSString *_languageStr;
    NSBundle *_bundle;
    NSString *_regId;
    NSString *_interval;
    NSArray *_hot_ad_array;
    long long _hot_interstitial_once;
    long long _hot_interstitial_count;
    long long _interstitial_once;
    long long _interstitial_count;
    long long _select_tfid;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property(nonatomic) long long select_tfid; // @synthesize select_tfid=_select_tfid;
@property(nonatomic) _Bool closeTyphoonCard; // @synthesize closeTyphoonCard=_closeTyphoonCard;
@property(nonatomic) _Bool isFirstLaunch; // @synthesize isFirstLaunch=_isFirstLaunch;
@property(nonatomic) long long interstitial_count; // @synthesize interstitial_count=_interstitial_count;
@property(nonatomic) long long interstitial_once; // @synthesize interstitial_once=_interstitial_once;
@property(nonatomic) long long hot_interstitial_count; // @synthesize hot_interstitial_count=_hot_interstitial_count;
@property(nonatomic) long long hot_interstitial_once; // @synthesize hot_interstitial_once=_hot_interstitial_once;
@property(retain, nonatomic) NSArray *hot_ad_array; // @synthesize hot_ad_array=_hot_ad_array;
@property(nonatomic) _Bool testInsertAd; // @synthesize testInsertAd=_testInsertAd;
@property(nonatomic) _Bool testTyphoon; // @synthesize testTyphoon=_testTyphoon;
@property(nonatomic) _Bool isShowInvite; // @synthesize isShowInvite=_isShowInvite;
@property(nonatomic) _Bool isAPPReview; // @synthesize isAPPReview=_isAPPReview;
@property(retain, nonatomic) NSString *interval; // @synthesize interval=_interval;
@property(retain, nonatomic) NSString *regId; // @synthesize regId=_regId;
@property(nonatomic) _Bool forbiddenMapGesture; // @synthesize forbiddenMapGesture=_forbiddenMapGesture;
@property(retain, nonatomic) NSBundle *bundle; // @synthesize bundle=_bundle;
@property(retain, nonatomic) NSString *languageStr; // @synthesize languageStr=_languageStr;
@property(copy, nonatomic) NSString *selectedAPPLanuage; // @synthesize selectedAPPLanuage=_selectedAPPLanuage;
@property(retain, nonatomic) NSCache *cache; // @synthesize cache=_cache;
- (id)imageForFeedbackAnnotationWithName:(id)arg1;
- (id)bundleForLanguageStr:(id)arg1;

@end

