//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface CYUtility : NSObject
{
}

+ (id)lang;
+ (id)ostype;
+ (_Bool)isThemeModeChangeWithVC:(id)arg1 traitCollection:(id)arg2;
+ (_Bool)isDarkMode;
+ (void)sendADStracInfoToServer:(unsigned long long)arg1 group:(id)arg2;
+ (void)sendNotificationSettingToServerWithVipStatus:(_Bool)arg1 weatherRemind:(_Bool)arg2 rainRemind:(_Bool)arg3 alertRemind:(_Bool)arg4 completionHandler:(CDUnknownBlockType)arg5;
+ (void)sendNotificationSettingToServerWithVipStatus:(_Bool)arg1 weatherRemind:(_Bool)arg2 completionHandler:(CDUnknownBlockType)arg3;
+ (void)sendNotificationSettingToServerWithVipStatus:(_Bool)arg1;
+ (void)sendNotificationSettingToServer;
+ (id)pingFangSemiboldWithFontSize:(double)arg1;
+ (id)pingFangRegularWithFontSize:(double)arg1;
+ (long long)convertFahrenheitToCelsius:(long long)arg1;
+ (long long)convertCelsiusToFahrenheit:(long long)arg1;
+ (id)clipImage:(id)arg1 rect:(struct CGRect)arg2;
+ (id)screenShot;
+ (id)weekStrByweekNum:(long long)arg1;
+ (_Bool)judgeCurrentTimeIsNightWithSunriseTime:(id)arg1 sunsetTime:(id)arg2 zoneOffset:(double)arg3;
+ (_Bool)judgeCurrentTimeIsNightWithSunriseTime:(id)arg1 sunsetTime:(id)arg2;
+ (id)stringWithHour:(long long)arg1 minute:(long long)arg2;
+ (long long)compareThisStrDate:(id)arg1 withThatStrDate:(id)arg2;
+ (double)percentOfOneMomentBetween24Hours:(id)arg1;
+ (double)percentOfNowInTodayWithZoneOffset:(double)arg1;
+ (double)percentOfNowInToday;
+ (long long)timeStartOfToday;
+ (long long)timeStartOfYesterday;
+ (id)localDateFromGMTDate:(id)arg1;
+ (id)localDateFromUnixTime:(id)arg1;
+ (id)convertTimestampToHHMMString:(double)arg1;
+ (id)convertTimestampToMMDDString:(double)arg1;
+ (id)convertTimestampToYYYYMMDDString:(double)arg1;
+ (id)convertTimestampToString:(double)arg1 format:(id)arg2;
+ (id)convertSecondsToHourString:(double)arg1;
+ (id)getAllAQILevelColorsArray;
+ (id)getAQIBarTranslucentColorFromAQIValue:(double)arg1;
+ (id)getAQIBarColorFromAQIValue:(double)arg1;
+ (id)getAQIImageNameFromValue:(double)arg1;
+ (id)getAQILevelStringFromValue:(double)arg1;
+ (id)getSkyconImageNameFromSkycon_old:(id)arg1;
+ (id)getSkyconImageNameFromSkycon:(id)arg1;
+ (id)getSkyconDescriptionFromSkycon_old:(id)arg1;
+ (id)getSkyconDescriptionFromSkycon:(id)arg1;
+ (id)computePercentColorFromStartColor:(id)arg1 endColor:(id)arg2 percent:(double)arg3;
+ (CDStruct_39925896)getColorPointFromUIColor:(id)arg1;
+ (id)getColorFromRainValue:(double)arg1 rainScheme:(int)arg2;
+ (int)getRainLevelFromRainValue:(double)arg1 rainScheme:(int)arg2;
+ (struct CGSize)getSizeWithContent:(id)arg1 font:(id)arg2;
+ (double)getWidthWithContent:(id)arg1 height:(double)arg2 font:(id)arg3;
+ (double)getHeightWithContent:(id)arg1 width:(double)arg2 font:(id)arg3;
+ (unsigned long long)currentSystemLanguage;
+ (id)bundleLanguageStringOfType:(unsigned long long)arg1;
+ (id)currentAPPLanguageString;
+ (unsigned long long)currentAPPLanguageType;
+ (id)timeForCloudType:(unsigned long long)arg1;
+ (double)distanceWithCoordinateA:(struct CLLocationCoordinate2D)arg1 coordinateB:(struct CLLocationCoordinate2D)arg2;
+ (id)urlWithAQIcoordinate:(struct CLLocationCoordinate2D)arg1;
+ (id)urlWithRain_Maplevel:(id)arg1 coordinate:(struct CLLocationCoordinate2D)arg2;
+ (id)urlWithType:(unsigned long long)arg1 product:(id)arg2 coordinate:(struct CLLocationCoordinate2D)arg3;
+ (_Bool)isImageHandleWithType:(unsigned long long)arg1;
+ (_Bool)isCloundWithType:(unsigned long long)arg1;
+ (double)hourlyCardCellWidth;
+ (double)angleWithWindDirection:(double)arg1;
+ (id)skyconTimeFromDateTime:(id)arg1;
+ (id)windPowerFromSpeed:(float)arg1;
+ (id)windDirectionFromAzimuth:(float)arg1;

@end

