//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AFNetworking/AFHTTPSessionManager.h>

@class WKWebView;

@interface YYNetworkTool : AFHTTPSessionManager
{
}

+ (id)requestWithURL:(id)arg1 andFilenName:(id)arg2 andVoiceData:(id)arg3;
+ (void)sessionGetWithUrlString:(id)arg1 parameters:(id)arg2 finished:(CDUnknownBlockType)arg3;
+ (id)requestWithURL:(id)arg1 andFilenName:(id)arg2 andImgData:(id)arg3;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedNetworkTool;
- (void)uploadImageData:(id)arg1 urlString:(id)arg2 parameters:(id)arg3 finished:(CDUnknownBlockType)arg4;
- (void)requesWithHeader:(id)arg1 method:(unsigned long long)arg2 urlString:(id)arg3 parameters:(id)arg4 finished:(CDUnknownBlockType)arg5;
- (void)requestWithUserToken:(id)arg1 method:(unsigned long long)arg2 urlString:(id)arg3 parameters:(id)arg4 finished:(CDUnknownBlockType)arg5;
- (void)requestWithToken:(id)arg1 method:(unsigned long long)arg2 urlString:(id)arg3 parameters:(id)arg4 finished:(CDUnknownBlockType)arg5;
- (void)request:(unsigned long long)arg1 urlString:(id)arg2 parameters:(id)arg3 finished:(CDUnknownBlockType)arg4;
- (void)configCommonHeader;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)getUserAgentCompletionHandler:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) WKWebView *webView;
- (void)new_request:(unsigned long long)arg1 urlString:(id)arg2 headParameters:(id)arg3 parameters:(id)arg4 finished:(CDUnknownBlockType)arg5;
- (void)loadHeadWithRequest:(id)arg1;
- (void)new_request:(unsigned long long)arg1 urlString:(id)arg2 parameters:(id)arg3 finished:(CDUnknownBlockType)arg4;

@end

