//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKit.h>

@interface KHStartController : UIViewController
{
}

- (void)noti_loginOut;
- (void)noti_click:(id)arg1;
- (void)dealloc;
- (void)viewDidLoad;
- (void)services_getAD;
- (_Bool)set_initInfo;
- (id)get_homeController;
- (void)kh_goHomeWithAnimDelay:(CGFloat)delay;

@end

