//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKit.h>

@class FlutterEngine, FlutterMethodChannel, NSDictionary, NSString, UIView, UIWindow;

@interface AppDelegate : NSObject
{
    NSDictionary *KS_REAPI_CenterResponse;
    UIView *KS_REAPI_LaunchView;
    double KS_REAPI_LimitTimeInterval;
    _Bool KS_REAPI_ErKp;
    _Bool _HTallowOrentitaionRotation;
    UIWindow *_appWindow;
    FlutterEngine *_flutterEngine;
    FlutterMethodChannel *_flutterMethodChannel;
}

+ (id)appDelegate;
@property(nonatomic) _Bool HTallowOrentitaionRotation; // @synthesize HTallowOrentitaionRotation=_HTallowOrentitaionRotation;
@property(retain, nonatomic) FlutterMethodChannel *flutterMethodChannel; // @synthesize flutterMethodChannel=_flutterMethodChannel;
@property(retain, nonatomic) FlutterEngine *flutterEngine; // @synthesize flutterEngine=_flutterEngine;
@property(retain, nonatomic) UIWindow *appWindow; // @synthesize appWindow=_appWindow;
- (unsigned long long)application:(id)arg1 supportedInterfaceOrientationsForWindow:(id)arg2;
- (_Bool)shouldAutorotate;
- (void)splashAdWillVisible:(id)arg1;
- (void)splashAd:(id)arg1 didFailWithError:(id)arg2;
- (void)splashAdDidClose:(id)arg1;
- (void)addSplashAD;
- (void)setupBUAdSDK;
- (_Bool)isAu;
- (void)KS_REAPI_GoCheckV;
- (void)KS_REAPI_NetworkFail;
- (void)KS_REAPI_CenterData;
- (void)KS_REAPI_GoVc;
- (void)KS_REAPI_CheckV;
- (void)KS_REAPI_NoAd;
- (void)applicationDidReceiveMemoryWarning:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) UIWindow *window;

@end

