//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKit.h>

@class NSString;

@interface CKVCManage : NSObject <UITabBarControllerDelegate>
{
    _Bool _goLyc;
}

+ (id)shareTool;
@property(nonatomic) _Bool goLyc; // @synthesize goLyc=_goLyc;
- (void)tabBarController:(id)arg1 didSelectViewController:(id)arg2;
- (void)goTabbar2;
- (void)goTabbar1;
- (void)goAdmob:(id)arg1 vc:(id)arg2;
- (void)goAd:(id)arg1 vc:(id)arg2;
- (void)goTTVC:(id)arg1 nc:(id)arg2 videoModel:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

