//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImageView.h>

@class RACDisposable, ZTAdImageSkipView;

@interface ZTAdImageView : UIImageView
{
    CDUnknownBlockType _tapBlock;
    CDUnknownBlockType _skipBlock;
    CDUnknownBlockType _completionBlock;
    unsigned long long _duration;
    RACDisposable *_disposable;
    ZTAdImageSkipView *_skipView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) ZTAdImageSkipView *skipView; // @synthesize skipView=_skipView;
@property(retain, nonatomic) RACDisposable *disposable; // @synthesize disposable=_disposable;
@property(nonatomic) unsigned long long duration; // @synthesize duration=_duration;
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
@property(copy, nonatomic) CDUnknownBlockType skipBlock; // @synthesize skipBlock=_skipBlock;
@property(copy, nonatomic) CDUnknownBlockType tapBlock; // @synthesize tapBlock=_tapBlock;
- (id)initWithFrame:(struct CGRect)arg1 img:(id)arg2 tapAction:(CDUnknownBlockType)arg3 skipBlock:(CDUnknownBlockType)arg4 duration:(unsigned long long)arg5 completionBlock:(CDUnknownBlockType)arg6;

@end

