//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel;

@interface ZTAdImageSkipView : UIView
{
    UILabel *_skipLabel;
    CDUnknownBlockType _actionBlock;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType actionBlock; // @synthesize actionBlock=_actionBlock;
@property(retain, nonatomic) UILabel *skipLabel; // @synthesize skipLabel=_skipLabel;
- (void)layoutSubviews;
- (void)setupViews;
- (void)setSkipStr:(id)arg1 duration:(unsigned long long)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

