//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface ADServer : NSObject
{
    _Bool isInterstialAvailable;
    NSString *trackidg;
}

+ (id)sharedServer;
@property(retain, nonatomic) NSString *trackidg; // @synthesize trackidg;
@property(nonatomic) _Bool isInterstialAvailable; // @synthesize isInterstialAvailable;
- (void)adtimingInterstitialDidFailToShow:(id)arg1 withError:(id)arg2;
- (void)adtimingInterstitialDidClose:(id)arg1;
- (void)adtimingInterstitialDidClick:(id)arg1;
- (void)adtimingInterstitialDidShow:(id)arg1;
- (void)adtimingInterstitialDidOpen:(id)arg1;
- (void)adtimingInterstitialChangedAvailability:(_Bool)arg1;
- (void)showAdInController:(id)arg1 forTrack:(id)arg2;
- (void)showAdInController:(id)arg1;
- (void)start;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

