//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class AppInfo, Downloads, JGProgressHUD, NSString, UIButton, UIImageView, UILabel, ipcList;

@interface AppsViewCell : UITableViewCell
{
    NSString *gTrackId;
    NSString *versionDev;
    Downloads *cdownload;
    JGProgressHUD *progresshud;
    UILabel *titleLabel;
    UILabel *subtitleLabel;
    UIImageView *iconView;
    ipcList *app;
    UIButton *installButton;
    AppInfo *gApp;
}

@property(retain, nonatomic) AppInfo *gApp; // @synthesize gApp;
@property(nonatomic) __weak UIButton *installButton; // @synthesize installButton;
@property(retain, nonatomic) ipcList *app; // @synthesize app;
@property(nonatomic) __weak UIImageView *iconView; // @synthesize iconView;
@property(nonatomic) __weak UILabel *subtitleLabel; // @synthesize subtitleLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel;
- (void)adClosed:(id)arg1;
- (void)setupElements:(id)arg1;
- (void)reloadCell:(id)arg1;
- (void)receivedZUNZStatus:(id)arg1;
- (void)receivedProgress:(id)arg1;
- (void)dismissprogreshud;
- (void)makehudrotar;
- (void)makehudtoprogress;
- (void)showProgressHud;
- (void)installApp:(id)arg1;
- (void)customizeCell;
- (void)setAppCell:(id)arg1;
- (void)disableButton;
- (void)enableButton;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (id)viewController;
- (void)awakeFromNib;

@end

