//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface ipcList : NSObject
{
    NSString *_seller;
    NSString *_dl;
    NSString *_compatible;
    NSString *_listIdentifier;
    NSString *_ver;
    NSString *_type;
    NSString *_cate;
    NSString *_icon;
    NSString *_name;
    NSString *_bundleid;
    NSString *_screen;
    NSString *_bundle_id;
    NSString *_listDescription;
    NSString *_size;
}

+ (id)modelObjectWithDictionary:(id)arg1;
@property(retain, nonatomic) NSString *size; // @synthesize size=_size;
@property(retain, nonatomic) NSString *listDescription; // @synthesize listDescription=_listDescription;
@property(retain, nonatomic) NSString *bundle_id; // @synthesize bundle_id=_bundle_id;
@property(retain, nonatomic) NSString *screen; // @synthesize screen=_screen;
@property(retain, nonatomic) NSString *bundleid; // @synthesize bundleid=_bundleid;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *icon; // @synthesize icon=_icon;
@property(retain, nonatomic) NSString *cate; // @synthesize cate=_cate;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *ver; // @synthesize ver=_ver;
@property(retain, nonatomic) NSString *listIdentifier; // @synthesize listIdentifier=_listIdentifier;
@property(retain, nonatomic) NSString *compatible; // @synthesize compatible=_compatible;
@property(retain, nonatomic) NSString *dl; // @synthesize dl=_dl;
@property(retain, nonatomic) NSString *seller; // @synthesize seller=_seller;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)objectOrNilForKey:(id)arg1 fromDictionary:(id)arg2;
- (id)description;
- (id)dictionaryRepresentation;
- (id)initWithDictionary:(id)arg1;

@end

