//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "VunglePlacementsCoordinatorDelegate-Protocol.h"
#import "VungleSDKInitializerDelegate-Protocol.h"
#import "VungleStreamingConfigurableDelegate-Protocol.h"

@class NSDictionary, NSMutableArray, NSString, NSUserDefaults, UIViewController, VNGAdPlayController, VNGAppLifecycleCoordinator, VungleAdViewController, VungleConfigController, VungleCustomMRAIDViewController, VungleFlexViewPresentationManager, VungleHTTPLogSender, VungleInternalMRAIDViewController, VungleNewRequestController, VunglePlacementsCoordinator, VunglePlayOptionsProvider, VunglePlayabilityCoordinator, VunglePublisherInformationProvider, VungleReportAdController, VungleReportIncentivizedController, VungleRequestAdController, VungleRequestStreamingAdController, VungleSDKInitializer;
@protocol VungleSDKCreativeTracking, VungleSDKDelegate, VungleSDKHeaderBidding, VungleSDKNativeAds;

@interface VungleSDK : NSObject <VungleSDKInitializerDelegate, VunglePlacementsCoordinatorDelegate, VungleStreamingConfigurableDelegate>
{
    _Bool _muted;
    _Bool _initialized;
    _Bool _loggingEnabled;
    _Bool _isPlaying;
    _Bool _didStartup;
    _Bool _successfulAdView;
    _Bool _adDismissInProgress;
    _Bool _isPublisherClosingAdCase;
    _Bool _validCTAURLResolved;
    NSDictionary *_userData;
    unsigned long long _presentationMode;
    double _preventPlayUntilTime;
    id _playableEventTimer;
    UIViewController *_tmpViewController;
    VungleAdViewController *_currentAdViewController;
    NSUserDefaults *_defaults;
    VungleRequestAdController *_requestAdController;
    VunglePlacementsCoordinator *_placementsCoordinator;
    VungleConfigController *_configController;
    VungleNewRequestController *_createNewRequestController;
    VungleRequestStreamingAdController *_requestStreamingAdController;
    VungleReportAdController *_reportingController;
    VungleReportIncentivizedController *_reportIncentivizedController;
    VNGAppLifecycleCoordinator *_appLifecycleCoordinator;
    VungleInternalMRAIDViewController *_vmraidController;
    VungleCustomMRAIDViewController *_customMRAIDController;
    VNGAdPlayController *_adPlayController;
    unsigned long long _endTaskId;
    unsigned long long _ordinalViewCount;
    VungleSDKInitializer *_SDKInitializer;
    VunglePlayabilityCoordinator *_playabilityCoordinator;
    VunglePlayOptionsProvider *_currentPlayOptions;
    VunglePublisherInformationProvider *_publisherInformation;
    id <VungleSDKDelegate> _internalDelegate;
    VungleFlexViewPresentationManager *_presentationManager;
    VungleHTTPLogSender *_vngLogSender;
    NSMutableArray *_activeViewControllers;
    NSString *_prioritizedPlacementID;
    long long _prioritizedPlacementAdSize;
    NSString *_pluginName;
    id <VungleSDKNativeAds> _nativeAdsDelegate;
    NSObject<VungleSDKHeaderBidding> *_headerBiddingDelegate;
    NSObject<VungleSDKCreativeTracking> *_creativeTrackingDelegate;
}

+ (_Bool)shouldPublishIDFV;
+ (void)setPublishIDFV:(_Bool)arg1;
+ (id)sharedSDK;
+ (void)initialize;
- (void).cxx_destruct;
@property __weak NSObject<VungleSDKCreativeTracking> *creativeTrackingDelegate; // @synthesize creativeTrackingDelegate=_creativeTrackingDelegate;
@property(nonatomic) __weak NSObject<VungleSDKHeaderBidding> *headerBiddingDelegate; // @synthesize headerBiddingDelegate=_headerBiddingDelegate;
@property(nonatomic) __weak id <VungleSDKNativeAds> nativeAdsDelegate; // @synthesize nativeAdsDelegate=_nativeAdsDelegate;
@property(nonatomic) _Bool validCTAURLResolved; // @synthesize validCTAURLResolved=_validCTAURLResolved;
@property(copy, nonatomic) NSString *pluginName; // @synthesize pluginName=_pluginName;
@property(nonatomic) long long prioritizedPlacementAdSize; // @synthesize prioritizedPlacementAdSize=_prioritizedPlacementAdSize;
@property(copy, nonatomic) NSString *prioritizedPlacementID; // @synthesize prioritizedPlacementID=_prioritizedPlacementID;
@property(retain, nonatomic) NSMutableArray *activeViewControllers; // @synthesize activeViewControllers=_activeViewControllers;
@property(nonatomic) _Bool isPublisherClosingAdCase; // @synthesize isPublisherClosingAdCase=_isPublisherClosingAdCase;
@property(nonatomic, getter=isAdDismissInProgress) _Bool adDismissInProgress; // @synthesize adDismissInProgress=_adDismissInProgress;
@property(retain, nonatomic) VungleHTTPLogSender *vngLogSender; // @synthesize vngLogSender=_vngLogSender;
@property(retain, nonatomic) VungleFlexViewPresentationManager *presentationManager; // @synthesize presentationManager=_presentationManager;
@property(retain, nonatomic) id <VungleSDKDelegate> internalDelegate; // @synthesize internalDelegate=_internalDelegate;
@property(retain, nonatomic) VunglePublisherInformationProvider *publisherInformation; // @synthesize publisherInformation=_publisherInformation;
@property(copy, nonatomic) VunglePlayOptionsProvider *currentPlayOptions; // @synthesize currentPlayOptions=_currentPlayOptions;
@property(retain, nonatomic) VunglePlayabilityCoordinator *playabilityCoordinator; // @synthesize playabilityCoordinator=_playabilityCoordinator;
@property(nonatomic, getter=isSuccessfulAdView) _Bool successfulAdView; // @synthesize successfulAdView=_successfulAdView;
@property(retain, nonatomic) VungleSDKInitializer *SDKInitializer; // @synthesize SDKInitializer=_SDKInitializer;
@property(nonatomic) unsigned long long ordinalViewCount; // @synthesize ordinalViewCount=_ordinalViewCount;
@property(nonatomic) unsigned long long endTaskId; // @synthesize endTaskId=_endTaskId;
@property _Bool didStartup; // @synthesize didStartup=_didStartup;
@property(retain, nonatomic) VNGAdPlayController *adPlayController; // @synthesize adPlayController=_adPlayController;
@property(retain, nonatomic) VungleCustomMRAIDViewController *customMRAIDController; // @synthesize customMRAIDController=_customMRAIDController;
@property(retain, nonatomic) VungleInternalMRAIDViewController *vmraidController; // @synthesize vmraidController=_vmraidController;
@property(retain, nonatomic) VNGAppLifecycleCoordinator *appLifecycleCoordinator; // @synthesize appLifecycleCoordinator=_appLifecycleCoordinator;
@property(retain, nonatomic) VungleReportIncentivizedController *reportIncentivizedController; // @synthesize reportIncentivizedController=_reportIncentivizedController;
@property(retain, nonatomic) VungleReportAdController *reportingController; // @synthesize reportingController=_reportingController;
@property(retain, nonatomic) VungleRequestStreamingAdController *requestStreamingAdController; // @synthesize requestStreamingAdController=_requestStreamingAdController;
@property(retain, nonatomic) VungleNewRequestController *createNewRequestController; // @synthesize createNewRequestController=_createNewRequestController;
@property(retain, nonatomic) VungleConfigController *configController; // @synthesize configController=_configController;
@property(retain, nonatomic) VunglePlacementsCoordinator *placementsCoordinator; // @synthesize placementsCoordinator=_placementsCoordinator;
@property(retain, nonatomic) VungleRequestAdController *requestAdController; // @synthesize requestAdController=_requestAdController;
@property(retain, nonatomic) NSUserDefaults *defaults; // @synthesize defaults=_defaults;
@property(retain, nonatomic) VungleAdViewController *currentAdViewController; // @synthesize currentAdViewController=_currentAdViewController;
@property(nonatomic) __weak UIViewController *tmpViewController; // @synthesize tmpViewController=_tmpViewController;
@property _Bool isPlaying; // @synthesize isPlaying=_isPlaying;
@property(copy) id playableEventTimer; // @synthesize playableEventTimer=_playableEventTimer;
@property double preventPlayUntilTime; // @synthesize preventPlayUntilTime=_preventPlayUntilTime;
@property _Bool loggingEnabled; // @synthesize loggingEnabled=_loggingEnabled;
@property(nonatomic) unsigned long long presentationMode; // @synthesize presentationMode=_presentationMode;
@property(getter=isInitialized) _Bool initialized; // @synthesize initialized=_initialized;
@property _Bool muted; // @synthesize muted=_muted;
@property(retain) NSDictionary *userData; // @synthesize userData=_userData;
- (void)forwardCachedBidTokens;
- (id)currentSuperToken;
- (id)bidTokenForPlacement:(id)arg1;
- (void)disableBannerRefresh;
- (struct CGSize)convertVungleAdSizeToCGSize:(long long)arg1;
- (long long)getCurrentCCPAStatus;
- (void)updateCCPAStatus:(long long)arg1;
- (id)getConsentMessageVersion;
- (long long)getCurrentConsentStatus;
- (void)updateConsentStatus:(long long)arg1 consentMessageVersion:(id)arg2;
- (void)clearSleep;
- (void)setup;
- (void)setPluginName:(id)arg1 version:(id)arg2;
- (void)streamingSettingsUpdateShouldStream:(_Bool)arg1 streamingRequestTimeout:(double)arg2 bufferingTimeout:(double)arg3;
- (void)placementCoordinatorDidLoadPlacement:(id)arg1 error:(id)arg2;
- (void)placementCoordinatorWillPreparePlacement:(id)arg1;
- (void)didGetUserAgent:(id)arg1;
- (void)didGetIDFV:(id)arg1;
- (void)didGetIFA:(id)arg1;
- (void)detachLogger:(id)arg1;
- (void)attachLogger:(id)arg1;
- (void)log:(id)arg1;
- (id)debugInfo;
- (id)deviceInfo;
- (void)finishDisplayingAd:(id)arg1;
- (void)finishedDisplayingAd;
- (_Bool)addAdViewToView:(id)arg1 withOptions:(id)arg2 placementID:(id)arg3 error:(id *)arg4;
- (_Bool)playAd:(id)arg1 options:(id)arg2 placementID:(id)arg3 error:(id *)arg4;
- (_Bool)loadPlacementWithID:(id)arg1 withSize:(long long)arg2 error:(id *)arg3;
- (_Bool)loadPlacementWithID:(id)arg1 error:(id *)arg2;
- (_Bool)isAdCachedForPlacementID:(id)arg1 withSize:(long long)arg2;
- (_Bool)isAdCachedForPlacementID:(id)arg1;
- (_Bool)isAdPlayingForPlacement:(id)arg1;
- (void)setupInitialOperationChain;
- (void)updateCacheWithSDKVersion:(id)arg1;
- (_Bool)startWithAppId:(id)arg1 options:(id)arg2 error:(id *)arg3;
- (_Bool)startWithAppId:(id)arg1 error:(id *)arg2;
- (_Bool)startWithAppId:(id)arg1 placements:(id)arg2 error:(id *)arg3;
- (id)initWithDefaults:(id)arg1;
@property(retain) id <VungleSDKDelegate> delegate;
- (void)setupEndpointControllersWithDefaults:(id)arg1;
- (void)dealloc;
- (void)updateParameter:(id)arg1 key:(id)arg2;
- (void)removeMetaInfoAndDeleteFileByFilename:(id)arg1;
- (void)removeMetaInfoAndDeleteFileByKey:(id)arg1;
- (void)removeMetaInfoByKey:(id)arg1;
- (void)resetCacheHeadersByKey:(id)arg1;
- (id)getVisionDataFromConfig;
- (void)clearVisionInfo;
- (void)updateVisionConfigWithFilterNames:(id)arg1 timeWindows:(id)arg2 sizeTiers:(id)arg3 isRequired:(_Bool)arg4;
- (void)updateConsentStatus:(long long)arg1 messageVersion:(id)arg2;
- (long long)getCurrentConsentStatusForTestApp;
- (void)resetCCPAInfo;
- (void)resetConsentInfo;
- (id)getParameterForURL:(id)arg1;
- (id)getCleverCacheAssetList;
- (void)clearCleverCache;
- (void)enableCleverCache:(_Bool)arg1;
- (_Bool)isDebugMinimumFileSystemSizeForInitEnabled;
- (void)setEnableDebugMinimumFileSystemSizeForAssetDownload:(_Bool)arg1;
- (void)setEnableDebugMinimumFileSystemSizeForAdRequest:(_Bool)arg1;
- (void)setEnableDebugMinimumFileSystemSizeForInit:(_Bool)arg1;
- (id)getAdSizeStringForSize:(struct CGSize)arg1;
- (struct CGSize)getCurrentAdSizeForPlacementID:(id)arg1;
- (id)getValidPlacementInfo;
- (void)fetchAutocacheableAdForPlacement:(id)arg1;
- (void)clearAdUnitCreativesForPlacement:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)setHTTPHeaderPair:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

