//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKit.h>

@class NSArray, NSDictionary, NSObject, NSString, PHAutomatedGetRenewalPolicyListAPIManager, PHCheckCouponInsuranceAPIManager, PHHealthCreditOutSideInvestmentAlertView, PHHealthCreditOutSideInvestmentManager, PHHealthCreditOutSideInvestmentModel, PHHomeActivityCoverAPIManager, PHHomeSearchComponentView, PHHomeSearchGetDefaultManager, PHHomeSearchGetDefaultModel, PHHomeSuspensionAPIManager, PHMessageBadgeView, PHMessageCheckAPIManager, PHQueryActivityAppPopupManager, PHSyncQueueExecutor, PHUploadCidAPIManager, PHVersionAPIManager, PHVitalityHomePageBasicDataAPIManager, TYAlertController, UIButton, UIImageView;
@protocol OS_dispatch_group, OS_dispatch_semaphore;

@interface PHTemplateViewController : UIViewController
{
    _Bool _isCheckInsuranceCouponAlert;
    _Bool _isFirstTimeViewAppear;
    _Bool _calledVersionApi;
    _Bool _isCheckHealthOutSideAlert;
    _Bool _isPushedFirstActivity;
    _Bool _isShowingRedPacketCommand;
    _Bool _isShowingAd;
    PHVersionAPIManager *_versionAPIManager;
    PHUploadCidAPIManager *_uploadCidAPIManager;
    PHHomeSearchGetDefaultManager *_searchGetDefaultManager;
    PHHealthCreditOutSideInvestmentManager *_healthOutSideInvestmentManager;
    PHVitalityHomePageBasicDataAPIManager *_vitalityHomePageBasicDataAPIManager;
    PHHomeActivityCoverAPIManager *_activityAPIManager;
    PHMessageCheckAPIManager *_messageCheckAPIManager;
    PHHomeSearchGetDefaultModel *_searchGetDefaultModel;
    PHHealthCreditOutSideInvestmentModel *_healthOutSideInvestmentModel;
    PHHomeSuspensionAPIManager *_suspensionAPIManager;
    PHCheckCouponInsuranceAPIManager *_checkInsuranceCouponAPIManager;
    PHAutomatedGetRenewalPolicyListAPIManager *_getRenewalPolicyList;
    NSDictionary *_activityDict;
    long long _loadActivityTimes;
    UIButton *_rightButton;
    id _getHealthDataCallBack;
    TYAlertController *_privacyPolicyController;
    PHMessageBadgeView *_badgeView;
    PHHealthCreditOutSideInvestmentAlertView *_healthOutSideInvestmentView;
    UIImageView *_suspensionView;
    UIButton *_suspensionCloseButton;
    NSString *_suspensionEventUrl;
    PHHomeSearchComponentView *_homeSearchView;
    PHSyncQueueExecutor *_alertQueue;
    NSObject<OS_dispatch_group> *_dispatchLoadGroup;
    NSDictionary *_policyDict;
    NSDictionary *_insuranceDict;
    PHQueryActivityAppPopupManager *_activityAppPopupManager;
    NSArray *_popupArray;
    NSObject<OS_dispatch_semaphore> *_semaphoreLock;
}

@property(retain, nonatomic) NSObject<OS_dispatch_semaphore> *semaphoreLock; // @synthesize semaphoreLock=_semaphoreLock;
@property(nonatomic) _Bool isShowingAd; // @synthesize isShowingAd=_isShowingAd;
@property(nonatomic) _Bool isShowingRedPacketCommand; // @synthesize isShowingRedPacketCommand=_isShowingRedPacketCommand;
@property(nonatomic) _Bool isPushedFirstActivity; // @synthesize isPushedFirstActivity=_isPushedFirstActivity;
@property(copy, nonatomic) NSArray *popupArray; // @synthesize popupArray=_popupArray;
@property(retain, nonatomic) PHQueryActivityAppPopupManager *activityAppPopupManager; // @synthesize activityAppPopupManager=_activityAppPopupManager;
@property(retain, nonatomic) NSDictionary *insuranceDict; // @synthesize insuranceDict=_insuranceDict;
@property(retain, nonatomic) NSDictionary *policyDict; // @synthesize policyDict=_policyDict;
@property(retain, nonatomic) NSObject<OS_dispatch_group> *dispatchLoadGroup; // @synthesize dispatchLoadGroup=_dispatchLoadGroup;
@property(retain, nonatomic) PHSyncQueueExecutor *alertQueue; // @synthesize alertQueue=_alertQueue;
@property(nonatomic) _Bool isCheckHealthOutSideAlert; // @synthesize isCheckHealthOutSideAlert=_isCheckHealthOutSideAlert;
@property(retain, nonatomic) PHHomeSearchComponentView *homeSearchView; // @synthesize homeSearchView=_homeSearchView;
@property(copy, nonatomic) NSString *suspensionEventUrl; // @synthesize suspensionEventUrl=_suspensionEventUrl;
@property(retain, nonatomic) UIButton *suspensionCloseButton; // @synthesize suspensionCloseButton=_suspensionCloseButton;
@property(retain, nonatomic) UIImageView *suspensionView; // @synthesize suspensionView=_suspensionView;
@property(retain, nonatomic) PHHealthCreditOutSideInvestmentAlertView *healthOutSideInvestmentView; // @synthesize healthOutSideInvestmentView=_healthOutSideInvestmentView;
@property(retain, nonatomic) PHMessageBadgeView *badgeView; // @synthesize badgeView=_badgeView;
@property(retain, nonatomic) TYAlertController *privacyPolicyController; // @synthesize privacyPolicyController=_privacyPolicyController;
@property(nonatomic) _Bool calledVersionApi; // @synthesize calledVersionApi=_calledVersionApi;
@property(copy, nonatomic) id getHealthDataCallBack; // @synthesize getHealthDataCallBack=_getHealthDataCallBack;
@property(nonatomic) _Bool isFirstTimeViewAppear; // @synthesize isFirstTimeViewAppear=_isFirstTimeViewAppear;
@property(retain, nonatomic) UIButton *rightButton; // @synthesize rightButton=_rightButton;
@property(nonatomic) long long loadActivityTimes; // @synthesize loadActivityTimes=_loadActivityTimes;
@property(retain, nonatomic) NSDictionary *activityDict; // @synthesize activityDict=_activityDict;
@property(retain, nonatomic) PHAutomatedGetRenewalPolicyListAPIManager *getRenewalPolicyList; // @synthesize getRenewalPolicyList=_getRenewalPolicyList;
@property(nonatomic) _Bool isCheckInsuranceCouponAlert; // @synthesize isCheckInsuranceCouponAlert=_isCheckInsuranceCouponAlert;
@property(retain, nonatomic) PHCheckCouponInsuranceAPIManager *checkInsuranceCouponAPIManager; // @synthesize checkInsuranceCouponAPIManager=_checkInsuranceCouponAPIManager;
@property(retain, nonatomic) PHHomeSuspensionAPIManager *suspensionAPIManager; // @synthesize suspensionAPIManager=_suspensionAPIManager;
@property(retain, nonatomic) PHHealthCreditOutSideInvestmentModel *healthOutSideInvestmentModel; // @synthesize healthOutSideInvestmentModel=_healthOutSideInvestmentModel;
@property(retain, nonatomic) PHHomeSearchGetDefaultModel *searchGetDefaultModel; // @synthesize searchGetDefaultModel=_searchGetDefaultModel;
@property(retain, nonatomic) PHMessageCheckAPIManager *messageCheckAPIManager; // @synthesize messageCheckAPIManager=_messageCheckAPIManager;
@property(retain, nonatomic) PHHomeActivityCoverAPIManager *activityAPIManager; // @synthesize activityAPIManager=_activityAPIManager;
@property(retain, nonatomic) PHVitalityHomePageBasicDataAPIManager *vitalityHomePageBasicDataAPIManager; // @synthesize vitalityHomePageBasicDataAPIManager=_vitalityHomePageBasicDataAPIManager;
@property(retain, nonatomic) PHHealthCreditOutSideInvestmentManager *healthOutSideInvestmentManager; // @synthesize healthOutSideInvestmentManager=_healthOutSideInvestmentManager;
@property(retain, nonatomic) PHHomeSearchGetDefaultManager *searchGetDefaultManager; // @synthesize searchGetDefaultManager=_searchGetDefaultManager;
@property(retain, nonatomic) PHUploadCidAPIManager *uploadCidAPIManager; // @synthesize uploadCidAPIManager=_uploadCidAPIManager;
@property(retain, nonatomic) PHVersionAPIManager *versionAPIManager; // @synthesize versionAPIManager=_versionAPIManager;
- (void)willEnterForeground;
- (void)requestWhenLogin;
- (void)clickRightMessageButton;
- (void)buildNavtiveView;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)addObserverLogin;
- (void)carouseViewCell:(id)arg1 didSelectItem:(id)arg2;
- (void)suspensionClosAction;
- (_Bool)prefersStatusBarHidden;
- (_Bool)compareVersionsFromAppStore:(id)arg1 WithAppVersion:(id)arg2;
- (void)showActive:(id)arg1;
- (void)didClickQuickEnterListForTest;
- (void)managerCallAPIDidFailed:(id)arg1;
- (void)managerCallAPIDidSuccess:(id)arg1;
- (id)paramsForApi:(id)arg1;
- (void)showHealthOutSideInvestment;
- (void)showInsuranceCouponAlertWithTitle:(id)arg1 message:(id)arg2;
- (void)showPolicyAlertWithCount:(long long)arg1 param:(id)arg2;
- (void)showCommonAlertWithImage:(id)arg1 routerString:(id)arg2;
- (void)showActivityPopupWithModel:(id)arg1;
- (void)handleCheckInsuranceCouponWithResult:(id)arg1;
- (void)showTipAlertWithArea:(id)arg1;
- (void)locatingComplete:(id)arg1;
- (void)handleLocation;
- (void)checkInsuranceCouponAlert;
- (void)loadCheckNewMessage;
- (void)loadhomeData;
- (void)loadVersionData;
- (void)goToRenewalInsuranceController;
- (void)parseRedPacketCommandOrRenewalInsurance;
- (void)checkRedPacketCommand;
- (void)requestFailed:(id)arg1;
- (void)requestSuccess:(id)arg1 itemList:(id)arg2;
- (void)requestDataFromServer;
- (_Bool)shouldShowBackButton;
- (_Bool)shouldLoadMemoryCache;
- (_Bool)shouldLoadFromNative;
- (_Bool)shouldLoadMockData;
- (id)customOperation;
- (id)getRequestParams;
- (id)getRequestMethod;
- (void)dealloc;
- (void)viewDidAppear:(_Bool)arg1;
- (void)loadFirstAlertView;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
@property(nonatomic) double scrollViewLastOffsetY;
- (void)scrollViewDidScroll:(id)arg1;
- (unsigned long long)getHostAPPLoginStatus;
- (void)onBackToLogin:(unsigned long long)arg1;
- (id)getAnydoorView;
- (void)buildAnyDoorView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

