//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKit.h>

@class IQKeyboardReturnKeyHandler, NSString, UIButton, UIImageView;

@interface BaseViewController : UIViewController <UITextFieldDelegate, UITextViewDelegate>
{
    UIViewController *_targetViewController;
    UIButton *_baseButton;
    UIImageView *_loadImageView;
    IQKeyboardReturnKeyHandler *_returnKeyHandler;
}

@property(retain, nonatomic) IQKeyboardReturnKeyHandler *returnKeyHandler; // @synthesize returnKeyHandler=_returnKeyHandler;
@property(retain, nonatomic) UIImageView *loadImageView; // @synthesize loadImageView=_loadImageView;
@property(retain, nonatomic) UIButton *baseButton; // @synthesize baseButton=_baseButton;
@property(retain, nonatomic) UIViewController *targetViewController; // @synthesize targetViewController=_targetViewController;
- (void)stopLoading;
- (void)startLoading;
- (void)tappedRightButton:(id)arg1;
- (void)tappedLeftButton:(id)arg1;
- (void)addSwipeRight;
- (void)addSwipeLeft;
- (void)rightButtonTouch;
- (void)leftButtonTouch;
- (void)showBarButton:(long long)arg1 control:(id)arg2;
- (void)showBarButton:(long long)arg1 button:(id)arg2;
- (void)showBarButton:(long long)arg1 image:(id)arg2;
- (void)showBarButton:(long long)arg1 title:(id)arg2 fontColor:(id)arg3;
- (void)back;
- (void)setupBack;
- (void)setupKeyboardHandler;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

