//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseViewController.h"

@class EmptyAdInfoModel, GuideView, HsadActionTypeActions, LaunchAdView, NSString;

@interface LaunchViewController : BaseViewController
{
    id _dismissCallback;
    GuideView *_guideView;
    LaunchAdView *_launchAdView;
    HsadActionTypeActions *_actions;
    EmptyAdInfoModel *_emptyModel;
}

@property(retain, nonatomic) EmptyAdInfoModel *emptyModel; // @synthesize emptyModel=_emptyModel;
@property(retain, nonatomic) HsadActionTypeActions *actions; // @synthesize actions=_actions;
@property(retain, nonatomic) LaunchAdView *launchAdView; // @synthesize launchAdView=_launchAdView;
@property(retain, nonatomic) GuideView *guideView; // @synthesize guideView=_guideView;
@property(copy, nonatomic) id dismissCallback; // @synthesize dismissCallback=_dismissCallback;
- (void)dealloc;
- (void)emptyAdOnClose;
- (void)emptyAdOnClick:(id)arg1;
- (void)emptyAdOnError;
- (void)emptyAdOnShow;
- (void)loadMargin;
- (_Bool)hsNativeSplashViewOnClick:(id)arg1 whetherHandleData:(id)arg2;
- (void)hsNativeSplashViewDidClose:(id)arg1;
- (void)hsNativeSplashViewWillClose:(id)arg1;
- (void)hsNativeSplashViewOnShow:(id)arg1;
- (void)hsNativeSplashViewOnFailed:(id)arg1 error:(id)arg2;
- (void)hsNativeSplashViewOnLoad:(id)arg1;
- (void)close;
- (void)guideViewDidDismiss;
- (_Bool)prefersStatusBarHidden;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

