//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITabBarController.h>

#import "CAAnimationDelegate-Protocol.h"
#import "JMessageDelegate-Protocol.h"
#import "UITabBarControllerDelegate-Protocol.h"
#import "_TtP12HandMetroSDK15HMTRSDKDelegate_-Protocol.h"

@class NSArray, NSString, UIButton, UILabel;

@interface MainTabBarController : UITabBarController <UITabBarControllerDelegate, CAAnimationDelegate, _TtP12HandMetroSDK15HMTRSDKDelegate_, JMessageDelegate>
{
    _Bool _hiddenStateBar;
    UILabel *_badgeLabel;
    NSArray *_vcNameArr;
    unsigned long long _lastSelectedIndex;
    UIButton *_couponToustBtn;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *couponToustBtn; // @synthesize couponToustBtn=_couponToustBtn;
@property(nonatomic) unsigned long long lastSelectedIndex; // @synthesize lastSelectedIndex=_lastSelectedIndex;
@property(nonatomic) _Bool hiddenStateBar; // @synthesize hiddenStateBar=_hiddenStateBar;
@property(retain, nonatomic) NSArray *vcNameArr; // @synthesize vcNameArr=_vcNameArr;
@property(retain, nonatomic) UILabel *badgeLabel; // @synthesize badgeLabel=_badgeLabel;
- (void)changeImageWithVC:(id)arg1 imageStr:(id)arg2 selImageStr:(id)arg3;
- (void)refreshTabIcons;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)addAnimation;
- (void)setSelectedIndex:(unsigned long long)arg1;
- (void)isHideBadge:(_Bool)arg1;
- (void)unReadMessage;
- (void)onReceiveMessageRetractEvent:(id)arg1;
- (void)onSyncOfflineMessageConversation:(id)arg1 offlineMessages:(id)arg2;
- (void)onSyncRoamingMessageConversation:(id)arg1;
- (void)onGroupInfoChanged:(id)arg1;
- (void)onConversationChanged:(id)arg1;
- (void)onReceiveMessage:(id)arg1 error:(id)arg2;
- (void)onReceiveUserLoginStatusChangeEvent:(id)arg1;
- (void)showCouponToust:(long long)arg1;
- (void)removeCouponToust;
- (void)showChatToustView:(long long)arg1;
- (void)showUserAgrementView;
- (void)tabBarController:(id)arg1 didSelectViewController:(id)arg2;
- (_Bool)tabBarController:(id)arg1 shouldSelectViewController:(id)arg2;
- (id)tabBarItemWithTitle:(id)arg1 image:(id)arg2 selectedImage:(id)arg3;
- (id)navigationControllerWithClass:(Class)arg1 title:(id)arg2 image:(id)arg3 selectedImage:(id)arg4;
- (void)matchFriend;
- (void)checkJumpToNewsVC;
- (id)customUITabarAppearance:(id)arg1 image:(id)arg2;
- (void)layoutSubs;
- (void)mobClick:(id)arg1 params:(id)arg2;
- (void)configRequest;
- (id)childViewControllerForStatusBarHidden;
- (_Bool)prefersStatusBarHidden;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

