//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseViewController.h"

@class AMapLocalWeatherLive, AMapSearchAPI, ConnectBannerAD, ConnectHeadView, HsadActionTypeActions, NSMutableArray, NSString, PNGCDCountDown, PNRightsResultModel, PNStationInfoModel, UITableView, UIView, UserModel;

@interface PNConnectionViewController : BaseViewController
{
    _Bool _firstToNews;
    UITableView *_tableView;
    ConnectHeadView *_headToolsView;
    UIView *_tableBackView;
    ConnectBannerAD *_bannerAD;
    double _historyY;
    double _frameUp;
    double _adHeight;
    double _stationHeight;
    double _menberHeight;
    double _headViewAllHeight;
    double _headViewLittleHeight;
    UserModel *_userModel;
    HsadActionTypeActions *_actions;
    NSMutableArray *_goodsRightArr;
    PNRightsResultModel *_homeRightsResultModel;
    PNStationInfoModel *_stationInfoModel;
    NSMutableArray *_noticeArr;
    AMapSearchAPI *_search;
    AMapLocalWeatherLive *_weatherLive;
    PNGCDCountDown *_gcdTimer;
}

@property(retain, nonatomic) PNGCDCountDown *gcdTimer; // @synthesize gcdTimer=_gcdTimer;
@property(retain, nonatomic) AMapLocalWeatherLive *weatherLive; // @synthesize weatherLive=_weatherLive;
@property(retain, nonatomic) AMapSearchAPI *search; // @synthesize search=_search;
@property(retain, nonatomic) NSMutableArray *noticeArr; // @synthesize noticeArr=_noticeArr;
@property(retain, nonatomic) PNStationInfoModel *stationInfoModel; // @synthesize stationInfoModel=_stationInfoModel;
@property(retain, nonatomic) PNRightsResultModel *homeRightsResultModel; // @synthesize homeRightsResultModel=_homeRightsResultModel;
@property(retain, nonatomic) NSMutableArray *goodsRightArr; // @synthesize goodsRightArr=_goodsRightArr;
@property(retain, nonatomic) HsadActionTypeActions *actions; // @synthesize actions=_actions;
@property(retain, nonatomic) UserModel *userModel; // @synthesize userModel=_userModel;
@property(nonatomic) _Bool firstToNews; // @synthesize firstToNews=_firstToNews;
@property(nonatomic) double headViewLittleHeight; // @synthesize headViewLittleHeight=_headViewLittleHeight;
@property(nonatomic) double headViewAllHeight; // @synthesize headViewAllHeight=_headViewAllHeight;
@property(nonatomic) double menberHeight; // @synthesize menberHeight=_menberHeight;
@property(nonatomic) double stationHeight; // @synthesize stationHeight=_stationHeight;
@property(nonatomic) double adHeight; // @synthesize adHeight=_adHeight;
@property(nonatomic) double frameUp; // @synthesize frameUp=_frameUp;
@property(nonatomic) double historyY; // @synthesize historyY=_historyY;
@property(retain, nonatomic) ConnectBannerAD *bannerAD; // @synthesize bannerAD=_bannerAD;
@property(retain, nonatomic) UIView *tableBackView; // @synthesize tableBackView=_tableBackView;
@property(retain, nonatomic) ConnectHeadView *headToolsView; // @synthesize headToolsView=_headToolsView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void)configUI;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)refreshToolsCell:(id)arg1 indexPath:(id)arg2;
- (void)refreshStationCell:(id)arg1 indexPath:(id)arg2;
- (void)refreshNewMemberCell:(id)arg1 indexPath:(id)arg2;
- (void)refreshBannerADCell:(id)arg1 indexPath:(id)arg2;
- (void)gotoNewsVC;
- (void)refreshUIWithHeadHeight:(double)arg1;
- (void)connectEndCallback;
- (void)connectingCallback;
- (void)connectSuccessCallback;
- (void)pushToMsgVC;
- (void)pushToCheckVC;
- (void)checkSpeed;
- (void)pushToQRCodeVC;
- (void)pushToMyVC;
- (void)pushToStationDetailVC;
- (void)tapWifiToFailVC;
- (void)tapWifiToGuideVC;
- (void)tapSignExchange:(id)arg1;
- (void)ADClickWithData:(id)arg1;
- (_Bool)isSignToday;
- (void)refreshHeadSignStatus;
- (void)showSignToust:(id)arg1;
- (void)requestSignInfoWithTap:(_Bool)arg1;
- (void)requestNoticeInfo;
- (void)requestStationInfo;
- (void)loadGCDTimer;
- (void)couponShowEvent;
- (void)checkMenberInfoTimeOut:(_Bool)arg1 index:(long long)arg2;
- (void)homeRightsRequest;
- (void)onWeatherSearchDone:(id)arg1 response:(id)arg2;
- (void)searchWeather;
- (void)dealloc;
- (void)appWillEnterForeground;
- (void)refreshConnectAd;
- (long long)preferredStatusBarStyle;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)reportIntegralTasks;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

