//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "EmptyAdViewDelegate-Protocol.h"

@class EmptyAdInfoModel, HsadActionTypeActions, LaunchAdView, NSString, UIViewController;

@interface PNLaunchADShowView : UIView <EmptyAdViewDelegate>
{
    CDUnknownBlockType _closeCallback;
    UIViewController *_fromVC;
    LaunchAdView *_launchAdView;
    HsadActionTypeActions *_actions;
    EmptyAdInfoModel *_emptyModel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) EmptyAdInfoModel *emptyModel; // @synthesize emptyModel=_emptyModel;
@property(retain, nonatomic) HsadActionTypeActions *actions; // @synthesize actions=_actions;
@property(retain, nonatomic) LaunchAdView *launchAdView; // @synthesize launchAdView=_launchAdView;
@property(retain, nonatomic) UIViewController *fromVC; // @synthesize fromVC=_fromVC;
@property(copy, nonatomic) CDUnknownBlockType closeCallback; // @synthesize closeCallback=_closeCallback;
- (void)emptyAdOnClose;
- (void)emptyAdOnClick:(id)arg1;
- (void)emptyAdOnError;
- (void)emptyAdOnShow;
- (void)loadMargin;
- (_Bool)hsNativeSplashViewOnClick:(id)arg1 whetherHandleData:(id)arg2;
- (void)hsNativeSplashViewDidClose:(id)arg1;
- (void)hsNativeSplashViewWillClose:(id)arg1;
- (void)hsNativeSplashViewOnShow:(id)arg1;
- (void)hsNativeSplashViewOnFailed:(id)arg1 error:(id)arg2;
- (void)hsNativeSplashViewOnLoad:(id)arg1;
- (void)close;
- (void)showLaunchViewFromVC:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

