//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSMutableArray, NSString, PublicButton, UILabel, UITableView, UIView;

@interface PNMemberBNewCell : UITableViewCell
{
    id _clickMoreBtnBlock;
    id _cuponClick;
    id _timeOutCallback;
    UIView *_backView;
    UILabel *_titleL;
    PublicButton *_moreBtn;
    UITableView *_cuponBenefitsTableView;
    NSMutableArray *_rightsArr;
}

+ (double)getHeight:(id)arg1;
@property(retain, nonatomic) NSMutableArray *rightsArr; // @synthesize rightsArr=_rightsArr;
@property(retain, nonatomic) UITableView *cuponBenefitsTableView; // @synthesize cuponBenefitsTableView=_cuponBenefitsTableView;
@property(retain, nonatomic) PublicButton *moreBtn; // @synthesize moreBtn=_moreBtn;
@property(retain, nonatomic) UILabel *titleL; // @synthesize titleL=_titleL;
@property(retain, nonatomic) UIView *backView; // @synthesize backView=_backView;
@property(copy, nonatomic) id timeOutCallback; // @synthesize timeOutCallback=_timeOutCallback;
@property(copy, nonatomic) id cuponClick; // @synthesize cuponClick=_cuponClick;
@property(copy, nonatomic) id clickMoreBtnBlock; // @synthesize clickMoreBtnBlock=_clickMoreBtnBlock;
- (void)clickMoreBtn;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)updateRightsInfo:(id)arg1;
- (void)cleanAllInfo;
- (void)layout;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

