//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKit.h>

@class NSString;

@interface ReportTaskService : NSObject
{
    _Bool _isRequesting;
}

+ (id)sharedInstance;
@property(nonatomic) _Bool isRequesting; // @synthesize isRequesting=_isRequesting;
- (id)readReportHandlerBlock:(id)arg1;
- (void)shareSuccess:(id)arg1;
- (id)requestShareWithArticleCode:(id)arg1 handlerBlock:(id)arg2;
- (id)tabBarController;
- (id)navigationController;
- (void)showLevelToustWithLevel:(long long)arg1;
- (void)getCardInfoWithExperience:(long long)arg1 level:(long long)arg2 addExperience:(long long)arg3;
- (void)reportExperience:(long long)arg1;
- (void)updateUserInfoWithExperience:(long long)arg1 level:(long long)arg2;
- (void)updateUserInfo:(long long)arg1;
- (void)reportDidAdView;
- (void)reportShareSuccessed;
- (void)reportLinkNetworkTask;
- (void)reportLiveTask;
- (void)reportNovelTask;
- (void)reportVideoTask;
- (void)reportArticleTask;
- (id)integralTaskReport:(long long)arg1 type:(long long)arg2 handlerBlock:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

