//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKit.h>

@class DTSplashBirthdayView, DTSplashScreenImage, DTSplashVideoView, DTWebImageView, NSTimer, UIButton, UIImageView, UIView, YYThreadSafeArray;

@interface DTSplashViewController : UIViewController
{
    _Bool _hasAppeared;
    DTSplashScreenImage *_splashScreenImage;
    id _completionBlock;
    UIImageView *_introImageView;
    UIButton *_detailButton;
    UIView *_bottomImageView;
    DTWebImageView *_logoView;
    DTSplashBirthdayView *_birthdayView;
    YYThreadSafeArray *_appendedBlocks;
    NSTimer *_timer;
    long long _duration;
    DTSplashVideoView *_videoView;
}

@property(retain, nonatomic) DTSplashVideoView *videoView; // @synthesize videoView=_videoView;
@property(nonatomic) long long duration; // @synthesize duration=_duration;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) _Bool hasAppeared; // @synthesize hasAppeared=_hasAppeared;
@property(retain, nonatomic) YYThreadSafeArray *appendedBlocks; // @synthesize appendedBlocks=_appendedBlocks;
@property(retain, nonatomic) DTSplashBirthdayView *birthdayView; // @synthesize birthdayView=_birthdayView;
@property(retain, nonatomic) DTWebImageView *logoView; // @synthesize logoView=_logoView;
@property(retain, nonatomic) UIView *bottomImageView; // @synthesize bottomImageView=_bottomImageView;
@property(retain, nonatomic) UIButton *detailButton; // @synthesize detailButton=_detailButton;
@property(retain, nonatomic) UIImageView *introImageView; // @synthesize introImageView=_introImageView;
@property(copy, nonatomic) id completionBlock; // @synthesize completionBlock=_completionBlock;
@property(retain, nonatomic) DTSplashScreenImage *splashScreenImage; // @synthesize splashScreenImage=_splashScreenImage;
- (void)generataExclusiveVideoViewIfNeeded;
- (void)splashFinishWithUrl:(id)arg1;
- (void)tapClick;
- (void)clickDetail;
- (void)timerFired:(id)arg1;
- (long long)splashShowTimeSeconds;
- (void)checkAppendedBlocksExectued;
- (void)appendMainThreadBlock:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)loadComponent;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

