//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSArray, NSDictionary, NSString, NVMProgressHUD, UIBarButtonItem, UIImage, UIView;
@protocol NVMViewControllerScrollDelegate;

@interface NVMViewController : UIViewController
{
    _Bool _didFirstAppear;
    _Bool _willFirstAppear;
    _Bool _isPeeked;
    _Bool _preferNavigationBarHiddenWhenAppear;
    _Bool _showAlternativeNavBar;
    _Bool _showCancelButton;
    _Bool _trackPageAppearance;
    _Bool _trackUTPageAppearance;
    _Bool _enableLeakCheck;
    _Bool _isPresenViewController;
    id nvm_result;
    NVMProgressHUD *_hud;
    NVMProgressHUD *_spinnerHud;
    NSArray *_targetTouchRedirectingViews;
    id _dismissBlock;
    id <NVMViewControllerScrollDelegate> _scrollDelegate;
    NSDictionary *_nvm_queryParams;
    NSDictionary *_pageMetaInfo;
    id _pageTrackParamsGenerator;
    NSString *_pageID;
    NSArray *_sourceRequestIDs;
    NSString *_controllerURI;
    UIBarButtonItem *_emptyBarButtonItem;
}

@property(nonatomic) _Bool isPresenViewController; // @synthesize isPresenViewController=_isPresenViewController;
@property(retain, nonatomic) UIBarButtonItem *emptyBarButtonItem; // @synthesize emptyBarButtonItem=_emptyBarButtonItem;
@property(nonatomic) _Bool enableLeakCheck; // @synthesize enableLeakCheck=_enableLeakCheck;
@property(copy, nonatomic) NSString *controllerURI; // @synthesize controllerURI=_controllerURI;
@property(retain, nonatomic) NSArray *sourceRequestIDs; // @synthesize sourceRequestIDs=_sourceRequestIDs;
@property(nonatomic) _Bool trackUTPageAppearance; // @synthesize trackUTPageAppearance=_trackUTPageAppearance;
@property(readonly, copy, nonatomic) NSString *pageID; // @synthesize pageID=_pageID;
@property(nonatomic) _Bool trackPageAppearance; // @synthesize trackPageAppearance=_trackPageAppearance;
@property(copy, nonatomic) id pageTrackParamsGenerator; // @synthesize pageTrackParamsGenerator=_pageTrackParamsGenerator;
@property(copy, nonatomic) NSDictionary *pageMetaInfo; // @synthesize pageMetaInfo=_pageMetaInfo;
@property(nonatomic, getter=isShowingCancelButton) _Bool showCancelButton; // @synthesize showCancelButton=_showCancelButton;
@property(nonatomic) _Bool showAlternativeNavBar; // @synthesize showAlternativeNavBar=_showAlternativeNavBar;
@property(nonatomic) _Bool preferNavigationBarHiddenWhenAppear; // @synthesize preferNavigationBarHiddenWhenAppear=_preferNavigationBarHiddenWhenAppear;
@property(copy, nonatomic) NSDictionary *nvm_queryParams; // @synthesize nvm_queryParams=_nvm_queryParams;
@property(nonatomic) __weak id <NVMViewControllerScrollDelegate> scrollDelegate; // @synthesize scrollDelegate=_scrollDelegate;
@property(copy, nonatomic) id dismissBlock; // @synthesize dismissBlock=_dismissBlock;
@property(copy, nonatomic) NSArray *targetTouchRedirectingViews; // @synthesize targetTouchRedirectingViews=_targetTouchRedirectingViews;
@property(nonatomic) _Bool isPeeked; // @synthesize isPeeked=_isPeeked;
@property(retain, nonatomic) NVMProgressHUD *spinnerHud; // @synthesize spinnerHud=_spinnerHud;
@property(retain, nonatomic) NVMProgressHUD *hud; // @synthesize hud=_hud;
@property(retain, nonatomic) id nvm_result; // @synthesize nvm_result;
- (void)dismissViewControllerAnimated:(_Bool)arg1 completion:(id)arg2;
- (void)presentViewController:(id)arg1 animated:(_Bool)arg2 completion:(id)arg3;
- (void)nvm_viewController:(id)arg1 finishOnResult:(id)arg2;
- (_Bool)isDescendantOfViewController:(id)arg1;
- (long long)indexInNavigationController;
- (void)popOrDissmissViewController:(_Bool)arg1;
- (long long)preferredStatusBarStyle;
- (id)navBarBackgroundImage;
- (_Bool)isNavigationControllerRootController;
- (void)setupEmptyLeftBarButtonItem;
@property(readonly, nonatomic) UIImage *navBarNormalImage;
@property(readonly, nonatomic) UIImage *navBarAlternativeImage;
- (void)configBackButton;
- (void)transitionNavigationBarChangeIfNeedWhenCan:(_Bool)arg1;
- (void)adjustNavigationBar;
- (void)addChildViewController:(id)arg1;
- (void)viewDidFirstAppear:(_Bool)arg1;
- (void)viewWillFirstAppear:(_Bool)arg1;
- (void)trackPVIfNeeded;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)nvm_showPopover:(id)arg1 anchor:(struct CGPoint)arg2;
- (_Bool)nvm_shouldUpdateForParentViewController;
- (id)nvm_barItemsByDeleteWebBarItemFromArray:(id)arg1;
- (void)nvm_itemClick:(id)arg1 title:(id)arg2;
- (void)nvm_removeRightBarItems;
- (void)nvm_showRightBarItems:(id)arg1;
- (id)nvm_navigationItem;
@property(copy, nonatomic) NSString *nvm_title;
@property(copy, nonatomic) UIView *nvm_titleView;
- (void)setNvm_rightBarButtonItems:(id)arg1 animated:(_Bool)arg2;
@property(retain, nonatomic) NSArray *nvm_rightBarButtonItems;
- (void)setNvm_rightBarButtonItem:(id)arg1 animated:(_Bool)arg2;
@property(retain, nonatomic) UIBarButtonItem *nvm_rightBarButtonItem;
- (void)setNvm_leftBarButtonItems:(id)arg1 animated:(_Bool)arg2;
@property(retain, nonatomic) NSArray *nvm_leftBarButtonItems;
- (void)setNvm_leftBarButtonItem:(id)arg1 animated:(_Bool)arg2;
@property(retain, nonatomic) UIBarButtonItem *nvm_leftBarButtonItem;
- (void)nvm_handleError:(id)arg1 retryAction:(id)arg2;
- (void)nvm_errorHandlerClear;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

