//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SSBaseView.h"

#import "BDReaderInsertViewProtocol-Protocol.h"

@class BDReaderModel, NSObject, NSString;
@protocol BDReaderInsertViewProtocol;

@interface SSChapterEndCommentContainerView : SSBaseView <BDReaderInsertViewProtocol>
{
    _Bool _isV5Style;
    NSObject<BDReaderInsertViewProtocol> *_commentObj;
    BDReaderModel *_readerModel;
    NSObject<BDReaderInsertViewProtocol> *_chaseObj;
    NSObject<BDReaderInsertViewProtocol> *_adObj;
    NSObject<BDReaderInsertViewProtocol> *_rewardObj;
    NSObject<BDReaderInsertViewProtocol> *_bookCircleObj;
}

@property(retain, nonatomic) NSObject<BDReaderInsertViewProtocol> *bookCircleObj; // @synthesize bookCircleObj=_bookCircleObj;
@property(retain, nonatomic) NSObject<BDReaderInsertViewProtocol> *rewardObj; // @synthesize rewardObj=_rewardObj;
@property(retain, nonatomic) NSObject<BDReaderInsertViewProtocol> *adObj; // @synthesize adObj=_adObj;
@property(retain, nonatomic) NSObject<BDReaderInsertViewProtocol> *chaseObj; // @synthesize chaseObj=_chaseObj;
@property(retain, nonatomic) BDReaderModel *readerModel; // @synthesize readerModel=_readerModel;
@property(retain, nonatomic) NSObject<BDReaderInsertViewProtocol> *commentObj; // @synthesize commentObj=_commentObj;
@property(nonatomic) _Bool isV5Style; // @synthesize isV5Style=_isV5Style;
- (void).cxx_destruct;
- (void)readerInsertedViewDidDisappear;
- (void)readerInsertedViewWillDisappear;
- (void)readerInsertedViewDidAppear;
- (void)readerInsertedViewWillAppear;
- (id)readerInsertedViewRequestInsertedView;
- (void)readerInsertedViewThemeConfigChange:(id)arg1;
- (void)readerInsertedViewBackgroundConfigChange:(id)arg1;
- (void)layoutSubviews;
- (id)initWithReaderModel:(id)arg1 commentObj:(id)arg2 chaseObj:(id)arg3 adObj:(id)arg4 rewardObj:(id)arg5 bookCircleObj:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

