//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKit.h>


@class BDReaderPageContext, NSString, UIPanGestureRecognizer, UITapGestureRecognizer;

@interface SSReadingAdBaseViewController : UIViewController
{
    _Bool _needUpdateSize;
    BDReaderPageContext *pageContext;
    double _showRate;
    UIPanGestureRecognizer *_pan;
    UITapGestureRecognizer *_tap;
}

@property(retain, nonatomic) UITapGestureRecognizer *tap; // @synthesize tap=_tap;
@property(retain, nonatomic) UIPanGestureRecognizer *pan; // @synthesize pan=_pan;
@property(nonatomic) double showRate; // @synthesize showRate=_showRate;
@property(nonatomic) _Bool needUpdateSize; // @synthesize needUpdateSize=_needUpdateSize;
@property(retain, nonatomic) BDReaderPageContext *pageContext; // @synthesize pageContext;
- (void).cxx_destruct;
- (_Bool)updateSizeIfNeeded:(struct CGSize)arg1;
- (void)setNeedUpdateSize;
- (void)onInsertedViewControllerShowRate:(float)arg1;
- (void)onInsertedViewControllerDidDisappear;
- (void)onInsertedViewControllerWillDisappear;
- (void)onInsertedViewControllerDidAppear;
- (void)onInsertedViewControllerWillAppear;
- (void)readerClientDidChangeSetting:(id)arg1 bookId:(id)arg2;
@property(readonly, nonatomic) _Bool isEnableTapPage;
@property(readonly, nonatomic) _Bool isInterruptAction;
@property(readonly, nonatomic) _Bool isEnableToolView;
- (void)dealColorWithObject:(id)arg1 configData:(id)arg2;
- (void)readerViewShowRate:(double)arg1;
- (id)getAdView;
- (id)getModel;
- (void)configDidChange;
- (void)setupViews;
- (void)readerViewDidDisappear;
- (void)readerViewWillDisappear;
- (void)readerViewDidAppear;
- (void)readerViewWillAppear;
- (void)dealloc;
- (void)viewDidLoad;
- (id)initWithModel:(id)arg1;
- (void)removeGestureRecognizers;
- (void)addGestureRecognizersToView:(id)arg1;
- (void)enableGestureRecognizers;
- (void)disableGestureRecognizers;
- (void)setupGestureRecognizersWithSel:(SEL)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

