//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSTimer, UIImage, UIImageView;

@interface MVSingleAnimatedImageView : UIView
{
    UIImage *_textureImage;
    UIImageView *_textureImageView;
    double _animationTickInterval;
    unsigned long long _numberOfFrames;
    NSTimer *_timer;
    long long _currentIndex;
    struct CGRect _singleImageFrame;
}

@property(nonatomic) long long currentIndex; // @synthesize currentIndex=_currentIndex;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) unsigned long long numberOfFrames; // @synthesize numberOfFrames=_numberOfFrames;
@property(nonatomic) struct CGRect singleImageFrame; // @synthesize singleImageFrame=_singleImageFrame;
@property(nonatomic) double animationTickInterval; // @synthesize animationTickInterval=_animationTickInterval;
@property(retain, nonatomic) UIImageView *textureImageView; // @synthesize textureImageView=_textureImageView;
@property(retain, nonatomic) UIImage *textureImage; // @synthesize textureImage=_textureImage;
- (void).cxx_destruct;
- (void)stopAnimation;
- (void)timerIsUp:(id)arg1;
- (void)startAnimation;
- (void)resetTiming;
- (id)initWithTextureImage:(id)arg1;

@end

