//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKit.h>

@class MVAdTagView, MVBannerModel, MVGIFImageView, MVPurePlayer, NSArray, NSString, NSTimer, UIButton, UIImageView, UITapGestureRecognizer, UIView;
@protocol MVSplashScreenDelegate;

@interface MVSplashScreenViewController : UIViewController
{
    double rate_;
    _Bool _dismissed;
    _Bool _complete;
    id <MVSplashScreenDelegate> _delegate;
    UITapGestureRecognizer *_tapGesture;
    UIView *_topContainer;
    UIImageView *_topSloganImageView;
    MVGIFImageView *_topImageView;
    MVPurePlayer *_topPlayer;
    MVAdTagView *_adTagView;
    UIButton *_muteButton;
    UIButton *_skipButton;
    UIView *_bottomContainer;
    UIImageView *_bottomIconImageView;
    MVBannerModel *_bannerModel;
    NSString *_currentUrl;
    NSString *_currentActionUrl;
    NSString *_deeplinkUrl;
    NSArray *_clickTrackingUrl;
    NSArray *_impressionTrackingUrl;
    NSTimer *_timer;
    long long _countDownNumber;
    NSString *_formatType;
}

@property(copy, nonatomic) NSString *formatType; // @synthesize formatType=_formatType;
@property(nonatomic) long long countDownNumber; // @synthesize countDownNumber=_countDownNumber;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) NSArray *impressionTrackingUrl; // @synthesize impressionTrackingUrl=_impressionTrackingUrl;
@property(retain, nonatomic) NSArray *clickTrackingUrl; // @synthesize clickTrackingUrl=_clickTrackingUrl;
@property(retain, nonatomic) NSString *deeplinkUrl; // @synthesize deeplinkUrl=_deeplinkUrl;
@property(retain, nonatomic) NSString *currentActionUrl; // @synthesize currentActionUrl=_currentActionUrl;
@property(retain, nonatomic) NSString *currentUrl; // @synthesize currentUrl=_currentUrl;
@property(nonatomic) _Bool complete; // @synthesize complete=_complete;
@property(nonatomic) _Bool dismissed; // @synthesize dismissed=_dismissed;
@property(retain, nonatomic) MVBannerModel *bannerModel; // @synthesize bannerModel=_bannerModel;
@property(retain, nonatomic) UIImageView *bottomIconImageView; // @synthesize bottomIconImageView=_bottomIconImageView;
@property(retain, nonatomic) UIView *bottomContainer; // @synthesize bottomContainer=_bottomContainer;
@property(retain, nonatomic) UIButton *skipButton; // @synthesize skipButton=_skipButton;
@property(retain, nonatomic) UIButton *muteButton; // @synthesize muteButton=_muteButton;
@property(retain, nonatomic) MVAdTagView *adTagView; // @synthesize adTagView=_adTagView;
@property(retain, nonatomic) MVPurePlayer *topPlayer; // @synthesize topPlayer=_topPlayer;
@property(retain, nonatomic) MVGIFImageView *topImageView; // @synthesize topImageView=_topImageView;
@property(retain, nonatomic) UIImageView *topSloganImageView; // @synthesize topSloganImageView=_topSloganImageView;
@property(retain, nonatomic) UIView *topContainer; // @synthesize topContainer=_topContainer;
@property(retain, nonatomic) UITapGestureRecognizer *tapGesture; // @synthesize tapGesture=_tapGesture;
@property(nonatomic) __weak id <MVSplashScreenDelegate> delegate; // @synthesize delegate=_delegate;
- (void)purePlayerDidFailToPlay:(id)arg1;
- (void)purePlayerDidPlayToEnd:(id)arg1;
- (void)purePlayer:(id)arg1 videoResolutionAvailable:(struct CGSize)arg2;
- (void)purePlayer:(id)arg1 playbackTimeChanged:(long long)arg2;
- (void)purePlayer:(id)arg1 videoDurationAvailable:(long long)arg2;
- (void)purePlayerIsReadyToPlay:(id)arg1;
- (void)setCountDown:(long long)arg1;
- (void)setMute:(_Bool)arg1;
- (void)muteButtonClicked;
- (void)loadPlayerWithUrl:(id)arg1 width:(long long)arg2 height:(long long)arg3 duration:(long long)arg4 keepVoice:(_Bool)arg5 showAdTag:(_Bool)arg6 banner:(id)arg7;
- (void)didEnterForeground:(id)arg1;
- (void)didEnterBackground:(id)arg1;
- (void)showSplashWithDelegate:(id)arg1;
- (_Bool)splashScreenExist;
- (void)handleTapGesture:(id)arg1;
- (double)displayTimeForSlogan;
- (double)expireTimeForLoadingBannerData;
- (void)timerScheduled:(id)arg1;
- (void)willShowBannerImage;
- (void)loadImageWithURL:(id)arg1;
- (void)showSloganImageView;
- (void)updateAdTag:(id)arg1;
- (void)refreshImageWithBanner:(id)arg1;
- (void)updateUIWithResponse:(id)arg1 error:(id)arg2;
- (void)requestBannerWithShareToken:(id)arg1 enable520Activity:(_Bool)arg2;
- (void)requestSplashAPI;
- (void)loadSplash;
- (void)dismiss;
- (void)skipButtonClicked;
- (void)privacyDidConfirm:(id)arg1;
- (id)spmValueForUserTrack;
- (id)pageNameForUserTrack;
- (_Bool)prefersStatusBarHidden;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

