//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface JXSystemInfo : NSObject
{
}

+ (id)getDeviceLocalIPAddress;
+ (double)getDeviceTotalCPUFrequency;
+ (double)getDeviceTotalMonery;
+ (_Bool)isAppStore;
+ (id)ipaddr;
+ (id)deviceScreenResolution;
+ (id)devResoluation;
+ (id)deviceFamily;
+ (id)clientInstallSource;
+ (id)jailBreaker;
+ (_Bool)isJailBroken;
+ (_Bool)is_iPhone_4;
+ (_Bool)is_iPhone_5;
+ (_Bool)is_iPhone_6;
+ (_Bool)is_iPhone_6plus;
+ (id)appBuildVersion;
+ (id)appVersion;
+ (id)systemTimeInfo;
+ (id)platform;
+ (id)osVersion;

@end

