//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KWAdvertisementBaseView.h"

@class KWSDWebImageView, UIButton, UILabel, UIView;

@interface KWAdvertisementForPlayerView : KWAdvertisementBaseView
{
    KWSDWebImageView *_imamgeView;
    UILabel *_titleLabel;
    UIView *_bgView;
    UILabel *_subTitleInfoLabel;
    UIButton *_closeButton;
}

@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) UILabel *subTitleInfoLabel; // @synthesize subTitleInfoLabel=_subTitleInfoLabel;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) KWSDWebImageView *imamgeView; // @synthesize imamgeView=_imamgeView;
- (void).cxx_destruct;
- (void)onShowTimerEnded;
- (void)onCloseBtnClicked:(id)arg1;
- (void)onTapGesture:(id)arg1;
- (void)hiddenPartOfView;
- (void)hiddenView;
- (void)showWithExpendAnimation:(_Bool)arg1;
- (void)layoutUIWithExpendAnimation:(_Bool)arg1;
- (void)initUI;
- (void)updateViewWith:(id)arg1;
- (void)dealloc;
- (void)commInit;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

