//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PlayerEventHandlerDelegate-Protocol.h"

@class KWAudioADModel, KWAudioADPosConfig, NSDate, NSString;

@interface KWAudioADManager : NSObject <PlayerEventHandlerDelegate>
{
    struct SendLogFlag _flag;
    _Bool _requestFlag;
    _Bool _checkNeedReqFlag;
    _Bool _checkNeedReqLongAudioFlag;
    _Bool _hasShownAudioAD;
    _Bool _requestingPosConfig;
    _Bool _shouldIgnoreFirstAD;
    int _prePlayMusicDuration;
    int _prePlayLongAudioDuration;
    int _preRequestADTime;
    int _adPlayOverTimeStemp;
    int _recallSmallADShowSeconds;
    KWAudioADPosConfig *_adPosConfig;
    KWAudioADModel *_adModel;
    NSDate *_preShowADDate;
    unsigned long long _preMediaItemId;
}

+ (id)defaultMgr;
@property(nonatomic) int recallSmallADShowSeconds; // @synthesize recallSmallADShowSeconds=_recallSmallADShowSeconds;
@property(nonatomic) unsigned long long preMediaItemId; // @synthesize preMediaItemId=_preMediaItemId;
@property(retain, nonatomic) NSDate *preShowADDate; // @synthesize preShowADDate=_preShowADDate;
@property(nonatomic) _Bool shouldIgnoreFirstAD; // @synthesize shouldIgnoreFirstAD=_shouldIgnoreFirstAD;
@property(nonatomic) int adPlayOverTimeStemp; // @synthesize adPlayOverTimeStemp=_adPlayOverTimeStemp;
@property(nonatomic) _Bool requestingPosConfig; // @synthesize requestingPosConfig=_requestingPosConfig;
@property(nonatomic) int preRequestADTime; // @synthesize preRequestADTime=_preRequestADTime;
@property(nonatomic) _Bool hasShownAudioAD; // @synthesize hasShownAudioAD=_hasShownAudioAD;
@property(nonatomic) _Bool checkNeedReqLongAudioFlag; // @synthesize checkNeedReqLongAudioFlag=_checkNeedReqLongAudioFlag;
@property(nonatomic) _Bool checkNeedReqFlag; // @synthesize checkNeedReqFlag=_checkNeedReqFlag;
@property(nonatomic) _Bool requestFlag; // @synthesize requestFlag=_requestFlag;
@property(nonatomic) int prePlayLongAudioDuration; // @synthesize prePlayLongAudioDuration=_prePlayLongAudioDuration;
@property(nonatomic) int prePlayMusicDuration; // @synthesize prePlayMusicDuration=_prePlayMusicDuration;
@property(retain, nonatomic) KWAudioADModel *adModel; // @synthesize adModel=_adModel;
@property(retain, nonatomic) KWAudioADPosConfig *adPosConfig; // @synthesize adPosConfig=_adPosConfig;
- (void).cxx_destruct;
- (_Bool)canClickSkip:(int)arg1;
- (_Bool)canClickSkip;
- (id)audioADItemInfo;
- (_Bool)needReqLongAudioAD:(id *)arg1;
- (_Bool)needReqAudioAD:(id *)arg1;
- (int)recallSmallADShowTotalSeconds;
- (void)updateRecallSmallADShowSeconds:(_Bool)arg1;
- (_Bool)needShowRecallSmallAD;
- (_Bool)shouldRecordMineAndDownloadSongs;
- (_Bool)needPlayAudioAD;
- (_Bool)canSkipAD;
- (void)adShowCountPlus;
- (id)showADCountKey;
- (void)p_checkSkipAudioAD;
- (void)playerChanged:(id)arg1;
- (void)vipStateDidChanged:(id)arg1;
- (void)onPlayStateChanged;
- (void)onPlayingItemChanged;
- (void)onScheduleChanged;
- (void)onSeekEvent;
- (void)getADInfo;
- (void)getADPosConfig;
- (void)checkNeedRequestPosConfig;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

