//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIImageView;

@interface KWBgImageAndPendantTipView : UIView
{
    CDUnknownBlockType _closeBgImageAndPendantTipViewBlock;
    UIImageView *_imageView;
    UIButton *_confirmButton;
}

@property(retain, nonatomic) UIButton *confirmButton; // @synthesize confirmButton=_confirmButton;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(copy, nonatomic) CDUnknownBlockType closeBgImageAndPendantTipViewBlock; // @synthesize closeBgImageAndPendantTipViewBlock=_closeBgImageAndPendantTipViewBlock;
- (void).cxx_destruct;
- (void)confirmAction;
- (void)layoutSubviews;
- (void)setUpViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

