//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class LocationManager, NSDate, NSString;

@interface KWKeyConfig : NSObject
{
    _Bool _isUserAuthorized;
    _Bool _isAllowUseMobileNet;
    int _ifUseMobileNet;
    int _nLastSelListId;
    int _playlistType;
    int _playingIndex;
    int _curPlayStat;
    int _playlistMode;
    int _kwPlayerType;
    int _kwPlaylistMode;
    int _kwAlbumMusicIndex;
    int _kwLiveMusicIndex;
    int _artistRadio_Control_Duration;
    int _statStartup;
    int _statForeground;
    int _existGuideMask;
    NSString *_userIp;
    NSString *_userArea;
    unsigned long long _rightRegionCode;
    unsigned long long _playlistId;
    unsigned long long _kwPlayAlbumID;
    NSString *_artistRadio_Control_TotastNext;
    NSString *_artistRadio_Control_TotastProgress;
    NSString *_keyStatStartup;
    NSString *_keyStatForeground;
    long long _totalStartup;
    NSDate *_appInstalledDate;
    NSString *_lastUpdateRemindDateTimeStr;
    long long _playRadioID;
    NSString *_playRadioName;
    NSString *_playRadioLibPath;
    NSString *_playRadioMediaItemJsonStr;
    LocationManager *_locManager;
    long long _overseasAimedDevice;
}

+ (_Bool)IsOnlyWifiConnectLimit;
+ (_Bool)IsCurrentNetworkWWAN;
+ (_Bool)IsCurrentNetworkWiFi;
+ (_Bool)IsCurrentNetworkValid;
+ (id)Instance;
+ (id)GetSecretUrl;
+ (id)GetWebTestUrl;
+ (id)GetPicInfoUrl;
+ (id)GetPicHost;
+ (_Bool)GetWebTestEnabled;
+ (_Bool)GetPicHostTestEnabled;
+ (const char *)GetRCMServerUrl;
+ (const char *)GetServerGameUrl;
+ (const char *)GetNMobiServerUrl;
+ (const char *)GetServerUrl;
+ (_Bool)NetworkStatusTrack:(const char *)arg1 result:(int)arg2;
+ (_Bool)CheckActivateState;
+ (_Bool)CheckUserAuthorization;
@property(nonatomic) long long overseasAimedDevice; // @synthesize overseasAimedDevice=_overseasAimedDevice;
@property(retain, nonatomic) LocationManager *locManager; // @synthesize locManager=_locManager;
@property(retain, nonatomic) NSString *playRadioMediaItemJsonStr; // @synthesize playRadioMediaItemJsonStr=_playRadioMediaItemJsonStr;
@property(retain, nonatomic) NSString *playRadioLibPath; // @synthesize playRadioLibPath=_playRadioLibPath;
@property(retain, nonatomic) NSString *playRadioName; // @synthesize playRadioName=_playRadioName;
@property(nonatomic) long long playRadioID; // @synthesize playRadioID=_playRadioID;
@property(copy, nonatomic) NSString *lastUpdateRemindDateTimeStr; // @synthesize lastUpdateRemindDateTimeStr=_lastUpdateRemindDateTimeStr;
@property(retain, nonatomic) NSDate *appInstalledDate; // @synthesize appInstalledDate=_appInstalledDate;
@property(nonatomic) int existGuideMask; // @synthesize existGuideMask=_existGuideMask;
@property(nonatomic) int statForeground; // @synthesize statForeground=_statForeground;
@property(nonatomic) int statStartup; // @synthesize statStartup=_statStartup;
@property(nonatomic) long long totalStartup; // @synthesize totalStartup=_totalStartup;
@property(copy, nonatomic) NSString *keyStatForeground; // @synthesize keyStatForeground=_keyStatForeground;
@property(copy, nonatomic) NSString *keyStatStartup; // @synthesize keyStatStartup=_keyStatStartup;
@property(retain, nonatomic) NSString *artistRadio_Control_TotastProgress; // @synthesize artistRadio_Control_TotastProgress=_artistRadio_Control_TotastProgress;
@property(retain, nonatomic) NSString *artistRadio_Control_TotastNext; // @synthesize artistRadio_Control_TotastNext=_artistRadio_Control_TotastNext;
@property(nonatomic) int artistRadio_Control_Duration; // @synthesize artistRadio_Control_Duration=_artistRadio_Control_Duration;
@property(nonatomic) _Bool isAllowUseMobileNet; // @synthesize isAllowUseMobileNet=_isAllowUseMobileNet;
@property(nonatomic) int kwLiveMusicIndex; // @synthesize kwLiveMusicIndex=_kwLiveMusicIndex;
@property(nonatomic) int kwAlbumMusicIndex; // @synthesize kwAlbumMusicIndex=_kwAlbumMusicIndex;
@property(nonatomic) unsigned long long kwPlayAlbumID; // @synthesize kwPlayAlbumID=_kwPlayAlbumID;
@property(nonatomic) int kwPlaylistMode; // @synthesize kwPlaylistMode=_kwPlaylistMode;
@property(nonatomic) int kwPlayerType; // @synthesize kwPlayerType=_kwPlayerType;
@property(nonatomic) int playlistMode; // @synthesize playlistMode=_playlistMode;
@property(nonatomic) int curPlayStat; // @synthesize curPlayStat=_curPlayStat;
@property(nonatomic) int playingIndex; // @synthesize playingIndex=_playingIndex;
@property(nonatomic) unsigned long long playlistId; // @synthesize playlistId=_playlistId;
@property(nonatomic) int playlistType; // @synthesize playlistType=_playlistType;
@property(nonatomic) int nLastSelListId; // @synthesize nLastSelListId=_nLastSelListId;
@property(nonatomic) int ifUseMobileNet; // @synthesize ifUseMobileNet=_ifUseMobileNet;
@property(nonatomic) unsigned long long rightRegionCode; // @synthesize rightRegionCode=_rightRegionCode;
@property(nonatomic) _Bool isUserAuthorized; // @synthesize isUserAuthorized=_isUserAuthorized;
@property(copy, nonatomic) NSString *userArea; // @synthesize userArea=_userArea;
@property(copy, nonatomic) NSString *userIp; // @synthesize userIp=_userIp;
- (void).cxx_destruct;
- (_Bool)currentRegionCodeIsChineseMainland;
- (void)recheckRegion;
- (_Bool)overseasCurrentDeviceIsFit;
- (void)saveOverseasAimedDevice:(unsigned long long)arg1;
- (void)saveUpdateRightRegionCode;
- (void)setInstallDateOfThisVersion:(id)arg1;
- (int)AddForegroundCount;
- (int)StartupCount;
- (_Bool)IsFirstTimeStartup;
- (_Bool)QualityPerfectIsNeedLogin;
- (int)AddStartupCount;
- (long long)daysFromAppInstalled;
- (_Bool)IsNewUser;
- (unsigned int)GetNowPlayingItemIndex:(unsigned int)arg1 playlistId:(unsigned long long)arg2;
- (_Bool)SetLocalMusicTag:(id)arg1;
- (id)GetLocalMusicTag;
- (_Bool)SetAlbumPlayingProgress:(int)arg1;
- (int)GetAlbumPlayingProgress;
- (_Bool)SetPlayingProgress:(int)arg1;
- (int)GetPlayingProgress;
- (_Bool)SetArtistRadioControl:(int)arg1 totastNext:(id)arg2 totastProgress:(id)arg3;
- (_Bool)SetPlaylist:(unsigned int)arg1 playlistId:(unsigned long long)arg2;
- (_Bool)GetPlaylist:(unsigned int *)arg1 playlistId:(unsigned long long *)arg2;
- (_Bool)SetPlayRadioMediaItemJsonStr:(id)arg1;
- (id)GetPlayRadioMediaItemJsonStr;
- (_Bool)SetPlayRadioID:(long long)arg1 radioName:(id)arg2 uiLogInfo:(id)arg3;
- (_Bool)GetPlayRadioID:(long long *)arg1 radioName:(id *)arg2 radioLibPath:(id *)arg3;
- (id)GetCurrentNetworkName;
- (void)SetPlayAuthorized:(_Bool)arg1;
- (_Bool)GetPlayAuthorized;
- (void)LoadKeyConfigFromDB;
- (void)LoadDefaultValue;

@end

