//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString, UIImage;

@interface KWMoreListItem : NSObject <NSCopying>
{
    _Bool _disable;
    int _menuId;
    NSString *_title;
    UIImage *_icon;
    UIImage *_highLightedIcon;
    UIImage *_disabledIcon;
    id _target;
    SEL _selector;
    id _obj;
}

+ (id)disableTitleColor:(_Bool)arg1 imageset:(long long)arg2;
+ (id)normalTitleColor:(_Bool)arg1 imageset:(long long)arg2;
+ (id)disableTitleColor:(_Bool)arg1;
+ (id)normalTitleColor:(_Bool)arg1;
+ (id)addCommonMenu:(int)arg1 target:(id)arg2 action:(SEL)arg3 obj:(id)arg4 imageset:(long long)arg5;
+ (id)qualityTitle:(id)arg1;
+ (id)titleForQulity:(int)arg1;
+ (id)addCommonMenu:(int)arg1 target:(id)arg2 action:(SEL)arg3 obj:(id)arg4;
+ (id)addCommonMenu:(int)arg1 target:(id)arg2 action:(SEL)arg3 obj:(id)arg4 disable:(_Bool)arg5 imageset:(long long)arg6;
+ (id)addCommonMenu:(int)arg1 target:(id)arg2 action:(SEL)arg3 obj:(id)arg4 disable:(_Bool)arg5;
+ (id)addMenuWithTitle:(id)arg1 image:(id)arg2 highlightedImage:(id)arg3 target:(id)arg4 action:(SEL)arg5 obj:(id)arg6;
@property(retain, nonatomic) id obj; // @synthesize obj=_obj;
@property SEL selector; // @synthesize selector=_selector;
@property id target; // @synthesize target=_target;
@property(retain, nonatomic) UIImage *disabledIcon; // @synthesize disabledIcon=_disabledIcon;
@property(retain, nonatomic) UIImage *highLightedIcon; // @synthesize highLightedIcon=_highLightedIcon;
@property(retain, nonatomic) UIImage *icon; // @synthesize icon=_icon;
@property(nonatomic) _Bool disable; // @synthesize disable=_disable;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) int menuId; // @synthesize menuId=_menuId;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

