//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "KWMusicFeeNeedPayTipsButtonBackViewDelegate-Protocol.h"

@class KWMusicFeeBaseBoxInfo, KWMusicFeeMemberImageView, KWMusicFeeNeedPayTipsButtonBackView, KWMusicFeePromotionTipView, KWMusicFeeTypeTipView, NSMutableArray, NSString, UIImageView, UILabel;
@protocol KWMusicFeeNeedPayTipsViewDelegate;

@interface KWMusicFeeNeedPayTipsView : UIView <KWMusicFeeNeedPayTipsButtonBackViewDelegate>
{
    _Bool _isOpenVip;
    id <KWMusicFeeNeedPayTipsViewDelegate> _delegate;
    CDUnknownBlockType _closeViewBlock;
    UIView *_backgroundView;
    UIView *_containView;
    KWMusicFeeMemberImageView *_headImageView;
    UILabel *_titleLabel;
    UILabel *_detailLabel;
    KWMusicFeeTypeTipView *_typeTipView;
    KWMusicFeePromotionTipView *_promotionView;
    KWMusicFeeNeedPayTipsButtonBackView *_buttonBackgroundView;
    UIImageView *_closeImageView;
    NSMutableArray *_tipsArray;
    UIView *_superView;
    KWMusicFeeBaseBoxInfo *_info;
}

+ (_Bool)queryIsAlbumOrSongPlayFee;
@property(retain, nonatomic) KWMusicFeeBaseBoxInfo *info; // @synthesize info=_info;
@property(retain, nonatomic) UIView *superView; // @synthesize superView=_superView;
@property(retain, nonatomic) NSMutableArray *tipsArray; // @synthesize tipsArray=_tipsArray;
@property(retain, nonatomic) UIImageView *closeImageView; // @synthesize closeImageView=_closeImageView;
@property(retain, nonatomic) KWMusicFeeNeedPayTipsButtonBackView *buttonBackgroundView; // @synthesize buttonBackgroundView=_buttonBackgroundView;
@property(retain, nonatomic) KWMusicFeePromotionTipView *promotionView; // @synthesize promotionView=_promotionView;
@property(retain, nonatomic) KWMusicFeeTypeTipView *typeTipView; // @synthesize typeTipView=_typeTipView;
@property(retain, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) KWMusicFeeMemberImageView *headImageView; // @synthesize headImageView=_headImageView;
@property(retain, nonatomic) UIView *containView; // @synthesize containView=_containView;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(nonatomic) _Bool isOpenVip; // @synthesize isOpenVip=_isOpenVip;
@property(copy, nonatomic) CDUnknownBlockType closeViewBlock; // @synthesize closeViewBlock=_closeViewBlock;
@property(nonatomic) __weak id <KWMusicFeeNeedPayTipsViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)didSelectItemsFromKWMusicFeeNeedPayTipsButtonBackView:(id)arg1;
- (void)closeViewClicked:(id)arg1;
- (void)showSuperView:(id)arg1;
- (void)setUpViews;
- (void)layoutSubviews;
- (void)updatebuttonBackgroundViewWithModelArray:(id)arg1;
- (void)updateImage:(id)arg1;
- (void)updateViewVithModel:(id)arg1 title:(id)arg2;
- (id)p_getMusicSongShortTitle;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

