//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class KWMarketVipInfo, KWMusicFeeUserAuthInfo, KWMusicPackageInfo, KWRoamPackageInfo, KWSuperVipInfo, KWURLSessionTask, KWVipInfo, NSArray, UIImage;

@interface KWMusicFeeUserManager : NSObject
{
    KWVipInfo *_vipInfo;
    struct CLock _lock;
    KWURLSessionTask *_vipRequestTask;
    KWMarketVipInfo *_marketVipInfo;
    KWRoamPackageInfo *_roamPackageInfo;
    KWMusicPackageInfo *_musicPackageInfo;
    KWSuperVipInfo *_superVipInfo;
    KWMusicFeeUserAuthInfo *_currentFeeUser;
    NSArray *_allFeeUsers;
}

+ (long long)fetchVipType;
+ (void)recordLastAccout;
+ (id)shareMgr;
@property(retain, nonatomic) NSArray *allFeeUsers; // @synthesize allFeeUsers=_allFeeUsers;
@property(retain, nonatomic) KWMusicFeeUserAuthInfo *currentFeeUser; // @synthesize currentFeeUser=_currentFeeUser;
@property(readonly, nonatomic) KWSuperVipInfo *superVipInfo; // @synthesize superVipInfo=_superVipInfo;
@property(readonly, nonatomic) KWMusicPackageInfo *musicPackageInfo; // @synthesize musicPackageInfo=_musicPackageInfo;
@property(readonly, nonatomic) KWRoamPackageInfo *roamPackageInfo; // @synthesize roamPackageInfo=_roamPackageInfo;
@property(readonly, nonatomic) KWMarketVipInfo *marketVipInfo; // @synthesize marketVipInfo=_marketVipInfo;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)getRightCircularIconByMusicPackgeState:(long long)arg1 superVipState:(long long)arg2 vipState:(long long)arg3 size:(long long)arg4 pageType:(long long)arg5 ignoreExpired:(_Bool)arg6;
- (id)getRightCircularIconByMusicPackgeState:(long long)arg1 superVipState:(long long)arg2 vipState:(long long)arg3 size:(long long)arg4 ignoreExpired:(_Bool)arg5;
- (id)getMyselfVipStateImageWithSize:(long long)arg1 ignoreExpired:(_Bool)arg2;
@property(readonly, nonatomic) UIImage *rightCircularIcon16x16;
@property(readonly, nonatomic) UIImage *rightSquareIcon_MyPage;
- (id)getRightCircularIconByMusicPackgeState:(long long)arg1 superVipState:(long long)arg2 vipState:(long long)arg3 size:(long long)arg4 pageType:(long long)arg5;
- (id)getRightCircularIconByMusicPackgeState:(long long)arg1 superVipState:(long long)arg2 vipState:(long long)arg3 size:(long long)arg4;
- (id)getRightCircularIconByMusicPackge:(id)arg1 superVip:(id)arg2 vip:(id)arg3 size:(long long)arg4;
- (struct KWUserMusicFeeMsg)getCurrentUserMusicFeeMsg;
@property(readonly, nonatomic) _Bool isAutoPaySuperVip;
@property(readonly, nonatomic) _Bool isSuperVipNeverSubscribe;
@property(readonly, nonatomic) _Bool isSuperVipExpire;
@property(readonly, nonatomic) _Bool isSuperVip;
@property(readonly, nonatomic) _Bool isVipNeverSubscribe;
@property(readonly, nonatomic) _Bool isVipExpire;
@property(readonly, nonatomic) _Bool isVip;
@property(readonly, nonatomic) KWVipInfo *vipInfo;
@property(readonly, nonatomic) _Bool isMusicPackageExpire;
@property(readonly, nonatomic) _Bool isMusicPackage;
- (void)requestUserVipInfo;
- (void)paramCurrentUserVIPInfoWithDic:(id)arg1;
- (void)paramMusicPackge:(id *)arg1 superVip:(id *)arg2 vip:(id *)arg3 marketVipInfo:(id *)arg4 roamPackageInfo:(id *)arg5 statusCode:(int *)arg6 fromDic:(id)arg7;
- (long long)getSuperVIPLeftDays;
- (long long)getMusicPackgeLeftDays;
- (void)cleanUserMuiscPackgeAndVipInfo;
- (void)cleanUserMusicPackgeInfo;
- (void)cleanUserVipInfo;
- (void)loadUserMusicPackgeAndVipInfoFromLocal;
- (void)p_requestVIPRecall;
- (void)rquestUserMusicPackgeAndVipInfoWithUid:(unsigned long long)arg1 complated:(CDUnknownBlockType)arg2;
- (void)onQueryUserVipNoticeComplete:(id)arg1;
- (void)requestUserVipNoticeInfoWithVipmExpire:(long long)arg1;
- (void)onNetworkChanged:(id)arg1;
- (void)onUserVipInfoChange:(id)arg1;
- (void)updateUserMusicPackageOrSuperVIPInfo;
- (void)updateUserInfo;
- (void)onMusicFeeUserInfoChange:(id)arg1;
- (void)onUserLoginStateChanged:(id)arg1;
- (int)parseQueryUserInfoResult:(id)arg1 withUid:(long long)arg2 toFeeUsers:(id *)arg3;
- (void)onQueryUserInfoComplete:(id)arg1 req:(id)arg2;
- (void)startQueryUserInfo;
- (void)loadFeeUserInfo;
- (void)virtualAccountStartQueryUserInfo;
- (id)currentUserNickName;
- (id)currentUserName;
- (long long)currentSessionId;
- (const char *)currentUserIdString;
- (long long)currentUserId;
- (_Bool)isValidMusicPackgeUser;
- (_Bool)isMusicPackgeExpired;
- (_Bool)isMarketing_VIP_1_0;
- (_Bool)isNewUser;
- (_Bool)isMusicPackgeUser;
- (_Bool)isLogin;
- (_Bool)isUserOnline;
- (void)removeObserverOfNotificationCenter;
- (void)addObserverOfNotificationCenter;
- (id)init;

@end

