//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface KWMusicFeeFlagObject : NSObject
{
    long long _musicFeeFlag;
}

+ (_Bool)allPlayAudioQualityIsFree:(long long)arg1;
+ (_Bool)queryCanPlay:(long long)arg1;
+ (_Bool)queryISVipPlay:(long long)arg1;
+ (_Bool)queryISVipDownload:(long long)arg1;
+ (_Bool)queryIsFeeAudioWithFeeFlag:(long long)arg1 audioQuality:(int)arg2 authType:(int)arg3;
+ (_Bool)queryIsFeeAudioVIPWithFeeFlag:(long long)arg1 audioQuality:(int)arg2 authType:(int)arg3;
@property(nonatomic) long long musicFeeFlag; // @synthesize musicFeeFlag=_musicFeeFlag;
- (_Bool)queryIsFee:(int)arg1 authType:(int)arg2 validQuality:(int *)arg3;
- (_Bool)queryIsFeeUseVIP:(int)arg1 authType:(int)arg2;
- (_Bool)queryIsFeeNoVIP:(int)arg1 authType:(int)arg2;
- (_Bool)queryIsFee:(int)arg1 authType:(int)arg2;
- (_Bool)queryIsFeeBySmooth:(int)arg1;
- (int)validVipPlayQuality;
- (int)validPlayQuality;
- (_Bool)feeFlag:(int)arg1 authType:(int)arg2 useVip:(_Bool)arg3 isAudio:(_Bool)arg4;
- (id)initWithFeeFlag:(long long)arg1;

@end

