//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class AutoScrollLabel, CAGradientLayer, KWSDWebImageView, KWSIconLabel, MediaItemInfo, UIImageView, UILabel;

@interface KWMusicFeeTipsAlertView : UIView
{
    _Bool _isOpenVip;
    _Bool _shouldFitiPhoneX;
    unsigned long long _tipAlertType;
    CAGradientLayer *_gradientLayer;
    KWSDWebImageView *_leftImageView;
    UILabel *_cotentLabel;
    AutoScrollLabel *_scrollTitleLabel;
    KWSIconLabel *_rightBtn;
    CDUnknownBlockType _closeBlock;
    MediaItemInfo *_mediaItem;
    CDUnknownBlockType _tipsClickBlock;
    UIImageView *_closeImageView;
}

+ (void)recordShowNumber:(unsigned long long)arg1;
+ (_Bool)musicFeeTipsCanShow:(unsigned long long)arg1;
+ (double)defaultHeightForiPhoneX;
+ (double)defaultHeight;
@property(retain, nonatomic) UIImageView *closeImageView; // @synthesize closeImageView=_closeImageView;
@property(nonatomic) _Bool shouldFitiPhoneX; // @synthesize shouldFitiPhoneX=_shouldFitiPhoneX;
@property(copy, nonatomic) CDUnknownBlockType tipsClickBlock; // @synthesize tipsClickBlock=_tipsClickBlock;
@property(retain, nonatomic) MediaItemInfo *mediaItem; // @synthesize mediaItem=_mediaItem;
@property(copy, nonatomic) CDUnknownBlockType closeBlock; // @synthesize closeBlock=_closeBlock;
@property(retain, nonatomic) KWSIconLabel *rightBtn; // @synthesize rightBtn=_rightBtn;
@property(retain, nonatomic) AutoScrollLabel *scrollTitleLabel; // @synthesize scrollTitleLabel=_scrollTitleLabel;
@property(retain, nonatomic) UILabel *cotentLabel; // @synthesize cotentLabel=_cotentLabel;
@property(retain, nonatomic) KWSDWebImageView *leftImageView; // @synthesize leftImageView=_leftImageView;
@property(retain, nonatomic) CAGradientLayer *gradientLayer; // @synthesize gradientLayer=_gradientLayer;
@property(nonatomic) unsigned long long tipAlertType; // @synthesize tipAlertType=_tipAlertType;
@property(nonatomic) _Bool isOpenVip; // @synthesize isOpenVip=_isOpenVip;
- (void).cxx_destruct;
- (void)manualCloseWindow;
- (void)onCloseImageViewTap;
- (void)tipsAllClickBlock:(CDUnknownBlockType)arg1;
- (void)closeViewWithBlock:(CDUnknownBlockType)arg1;
- (void)showView:(id)arg1 top:(double)arg2;
- (void)udpateTips:(id)arg1 buttonTitle:(id)arg2;
- (void)updateModelWithItemInfo:(id)arg1;
- (void)updateModel:(id)arg1 appendText:(id)arg2;
- (void)layoutSubviews;
- (void)p_layout;
- (void)setUpViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

