//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KWCellViewModel.h"

@class KWMusicBanginfo, NSString;

@interface KWMusicCellViewModel : KWCellViewModel
{
    _Bool _notShowCopyRight;
    _Bool _showSectionIndex;
    _Bool _dontShowAlbumMenu;
    _Bool _isCurrentMusic;
    _Bool _showKuwoAnchorProgress;
    int _showRanking;
    long long _index;
    long long _publicCellType;
    NSString *_sourceCurrentCell;
    KWMusicBanginfo *_bangInfo;
}

+ (id)musicCellVMWithSingleItem:(id)arg1;
@property(retain, nonatomic) KWMusicBanginfo *bangInfo; // @synthesize bangInfo=_bangInfo;
@property(nonatomic) _Bool showKuwoAnchorProgress; // @synthesize showKuwoAnchorProgress=_showKuwoAnchorProgress;
@property(copy, nonatomic) NSString *sourceCurrentCell; // @synthesize sourceCurrentCell=_sourceCurrentCell;
@property(nonatomic) _Bool isCurrentMusic; // @synthesize isCurrentMusic=_isCurrentMusic;
@property(nonatomic) _Bool dontShowAlbumMenu; // @synthesize dontShowAlbumMenu=_dontShowAlbumMenu;
@property(nonatomic) _Bool showSectionIndex; // @synthesize showSectionIndex=_showSectionIndex;
@property(nonatomic) _Bool notShowCopyRight; // @synthesize notShowCopyRight=_notShowCopyRight;
@property(nonatomic) long long publicCellType; // @synthesize publicCellType=_publicCellType;
@property(nonatomic) int showRanking; // @synthesize showRanking=_showRanking;
@property(nonatomic) long long index; // @synthesize index=_index;
- (void).cxx_destruct;
- (long long)ascCompareArtist:(id)arg1;
- (long long)ascCompareTitle:(id)arg1;
- (void)checkCurrentCell;
- (double)cellHeightForIndexPath:(id)arg1;
- (id)cellForCellViewModelWithDelegate:(id)arg1 tableView:(id)arg2 indexPath:(id)arg3;
- (id)init;

@end

