//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class KWSDWebImageView, NSArray, NSMutableArray, UILabel;
@protocol KWSearchRecommandTipsViewDelegate;

@interface KWSearchRecommandTipsView : UIView
{
    long long _preferLineCount;
    int _kwSearchType;
    id <KWSearchRecommandTipsViewDelegate> _recommandTipsDelegate;
    UILabel *_tintLabelView;
    UIView *_tipsBtnsContainer;
    NSMutableArray *_tipsBtnsArray;
    NSArray *_recommandTipsCaches;
    KWSDWebImageView *_businessAdTipImageView;
}

@property(retain, nonatomic) KWSDWebImageView *businessAdTipImageView; // @synthesize businessAdTipImageView=_businessAdTipImageView;
@property(retain, nonatomic) NSArray *recommandTipsCaches; // @synthesize recommandTipsCaches=_recommandTipsCaches;
@property(retain, nonatomic) NSMutableArray *tipsBtnsArray; // @synthesize tipsBtnsArray=_tipsBtnsArray;
@property(retain, nonatomic) UIView *tipsBtnsContainer; // @synthesize tipsBtnsContainer=_tipsBtnsContainer;
@property(retain, nonatomic) UILabel *tintLabelView; // @synthesize tintLabelView=_tintLabelView;
@property(nonatomic) int kwSearchType; // @synthesize kwSearchType=_kwSearchType;
@property(nonatomic) __weak id <KWSearchRecommandTipsViewDelegate> recommandTipsDelegate; // @synthesize recommandTipsDelegate=_recommandTipsDelegate;
- (void).cxx_destruct;
- (void)reLoadRecommandTip_MusicWithPersistendId:(long long)arg1;
- (void)reLoadRecommandTipsWithId:(long long)arg1;
- (void)didSelectSearchString:(id)arg1;
- (void)refreshTipButtons;
- (void)buinessAdTipTap:(id)arg1;
- (void)layoutSubviews;
- (void)updateBusinessTipImageViewPosition;
- (void)loadBusinessSearchTipImageView;
- (id)initWithFrame:(struct CGRect)arg1;
- (double)preferHeight;

@end

