//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseCell.h"

@class UIButton;

@interface KWSearchPlayBarCell : BaseCell
{
    UIButton *_playAllBtn;
    UIButton *_batchOperationBtn;
}

+ (double)cellHeight;
@property(retain, nonatomic) UIButton *batchOperationBtn; // @synthesize batchOperationBtn=_batchOperationBtn;
@property(retain, nonatomic) UIButton *playAllBtn; // @synthesize playAllBtn=_playAllBtn;
- (void).cxx_destruct;
- (void)onBatchOperationBtnClicked:(id)arg1;
- (void)onAllPlayBtnClicked:(id)arg1;
- (void)updateCellUseCellVMwithIndexPath:(id)arg1;
- (void)layoutSubviews;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)_commonInit;
- (id)init;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

