//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "OperationLogProtocol-Protocol.h"

@class KWUILogInfo, NSArray, NSDictionary, NSString;

@interface KWSplashAdInfoModel : NSObject <OperationLogProtocol>
{
    _Bool _sourceFileIsLocal;
    _Bool _useTencentSplashAd;
    _Bool _flowSwitch;
    long long _adType;
    NSString *_sourceUrl;
    NSString *_sourceFilePath;
    unsigned long long _picID;
    NSDictionary *_clickConf;
    NSString *_ad_text_id;
    double _adShowDuration;
    NSString *_channelNums;
    NSArray *_report_url_show;
    NSArray *_report_url_click;
    double _width;
    double _height;
    NSString *_corner;
    NSString *_subtitle;
    NSString *_h5ImgUrl;
    KWUILogInfo *_uiLogInfo;
    NSString *_fileName;
}

+ (id)hashFileName:(id)arg1;
+ (id)picFilePathWithFileName:(id)arg1;
+ (void)downloadAdPictureWithUrl:(id)arg1;
+ (void)downloadAdSourceWith:(id)arg1;
+ (_Bool)p_checkAdPicture:(id)arg1;
+ (id)spalshAdWithInfo:(id)arg1;
@property(copy, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
@property(copy, nonatomic) KWUILogInfo *uiLogInfo; // @synthesize uiLogInfo=_uiLogInfo;
@property(nonatomic) _Bool flowSwitch; // @synthesize flowSwitch=_flowSwitch;
@property(copy, nonatomic) NSString *h5ImgUrl; // @synthesize h5ImgUrl=_h5ImgUrl;
@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(copy, nonatomic) NSString *corner; // @synthesize corner=_corner;
@property(nonatomic) double height; // @synthesize height=_height;
@property(nonatomic) double width; // @synthesize width=_width;
@property(nonatomic) _Bool useTencentSplashAd; // @synthesize useTencentSplashAd=_useTencentSplashAd;
@property(retain, nonatomic) NSArray *report_url_click; // @synthesize report_url_click=_report_url_click;
@property(retain, nonatomic) NSArray *report_url_show; // @synthesize report_url_show=_report_url_show;
@property(copy, nonatomic) NSString *channelNums; // @synthesize channelNums=_channelNums;
@property(nonatomic) double adShowDuration; // @synthesize adShowDuration=_adShowDuration;
@property(copy, nonatomic) NSString *ad_text_id; // @synthesize ad_text_id=_ad_text_id;
@property(retain, nonatomic) NSDictionary *clickConf; // @synthesize clickConf=_clickConf;
@property(nonatomic) unsigned long long picID; // @synthesize picID=_picID;
@property(nonatomic) _Bool sourceFileIsLocal; // @synthesize sourceFileIsLocal=_sourceFileIsLocal;
@property(copy, nonatomic) NSString *sourceFilePath; // @synthesize sourceFilePath=_sourceFilePath;
@property(copy, nonatomic) NSString *sourceUrl; // @synthesize sourceUrl=_sourceUrl;
@property(nonatomic) long long adType; // @synthesize adType=_adType;
- (void).cxx_destruct;
- (id)operationLogInfo;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

