//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseNaviViewController.h"

#import "KWMusicFeePayWebUIViewControllerDelegate-Protocol.h"
#import "KWStarThemeDownloadManagerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class KWSDWebImageView, KWSkinProgressButton, KWSkinThemeDetailImageScrollView, KWStarThemeInfo, KWStarThemeSkinNetwork, KWThemeFeeInfo, NSArray, NSMutableArray, NSString, UILabel, UIScrollView, UIView;

@interface KWStarThemeDetailViewController : BaseNaviViewController <KWMusicFeePayWebUIViewControllerDelegate, KWStarThemeDownloadManagerDelegate, UIScrollViewDelegate>
{
    _Bool _watingDownload;
    long long _skinListType;
    UIScrollView *_contentView;
    KWSDWebImageView *_blurImageView;
    UILabel *_titleLabel;
    UILabel *_sizeLabel;
    UILabel *_descrLabel;
    KWSkinProgressButton *_btn;
    KWSkinThemeDetailImageScrollView *_imagesContentView;
    NSMutableArray *_preViewImageViews;
    NSMutableArray *_preViewShadowLayers;
    NSArray *_preViewImageUrls;
    KWStarThemeInfo *_themeInfo;
    KWStarThemeSkinNetwork *_network;
    KWThemeFeeInfo *_feeInfo;
    NSArray *_feeInfos;
    UIView *_infoContentView;
}

+ (void)p_msgBoxForUnusedSkin:(id)arg1;
+ (id)tintImageWithImage:(id)arg1 tintColor:(id)arg2;
@property(retain, nonatomic) UIView *infoContentView; // @synthesize infoContentView=_infoContentView;
@property(nonatomic) _Bool watingDownload; // @synthesize watingDownload=_watingDownload;
@property(retain, nonatomic) NSArray *feeInfos; // @synthesize feeInfos=_feeInfos;
@property(retain, nonatomic) KWThemeFeeInfo *feeInfo; // @synthesize feeInfo=_feeInfo;
@property(retain, nonatomic) KWStarThemeSkinNetwork *network; // @synthesize network=_network;
@property(retain, nonatomic) KWStarThemeInfo *themeInfo; // @synthesize themeInfo=_themeInfo;
@property(retain, nonatomic) NSArray *preViewImageUrls; // @synthesize preViewImageUrls=_preViewImageUrls;
@property(retain, nonatomic) NSMutableArray *preViewShadowLayers; // @synthesize preViewShadowLayers=_preViewShadowLayers;
@property(retain, nonatomic) NSMutableArray *preViewImageViews; // @synthesize preViewImageViews=_preViewImageViews;
@property(retain, nonatomic) KWSkinThemeDetailImageScrollView *imagesContentView; // @synthesize imagesContentView=_imagesContentView;
@property(retain, nonatomic) KWSkinProgressButton *btn; // @synthesize btn=_btn;
@property(retain, nonatomic) UILabel *descrLabel; // @synthesize descrLabel=_descrLabel;
@property(retain, nonatomic) UILabel *sizeLabel; // @synthesize sizeLabel=_sizeLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) KWSDWebImageView *blurImageView; // @synthesize blurImageView=_blurImageView;
@property(retain, nonatomic) UIScrollView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) long long skinListType; // @synthesize skinListType=_skinListType;
- (void).cxx_destruct;
- (void)updateUI;
- (_Bool)loadSkin:(struct CSkin *)arg1;
- (void)setCurrentSkinThemeWithInfo:(id)arg1;
- (void)transformImages;
- (void)scrollViewDidScroll:(id)arg1;
- (void)unreg_observer_event;
- (void)reg_observer_event;
- (id)forDownloadItem;
- (void)starThemeDownloadSuccess;
- (void)starThemeDownloadFailed;
- (void)starThemeDownloadProgress:(double)arg1;
- (void)checkCanbeUpgreadeWithThemeInfo:(id)arg1;
- (void)upgradeStarTheme;
- (void)fetchStarThemeDetailWhitId:(id)arg1;
- (void)KWMusicFeePayDoneResult:(_Bool)arg1 payCancel:(_Bool)arg2 musicFeeBuyType:(int)arg3 payForOperation:(int)arg4 payForMusicInfos:(id)arg5 payForAlbumInfos:(id)arg6 payUserdata:(id)arg7;
- (void)queryAlbumSongsWithId:(long long)arg1;
- (void)gotoAlbumPayView;
- (void)gotoSongPayView;
- (void)gotoVIPPayView:(_Bool)arg1;
- (void)gotoFirstLevRedirectUrl;
- (void)downloadAndUserTheme;
- (void)musicPackageAndSuperVIPDeal;
- (void)pushLoginViewControllerWithInfo:(id)arg1;
- (void)onBtnClicked:(id)arg1;
- (void)onPreviewImageTap:(id)arg1;
- (id)composeImage:(id)arg1 withImage:(id)arg2 withIconImage:(id)arg3;
- (void)setBlurBackImage:(id)arg1;
- (unsigned long long)getTintColor;
- (void)updatePrevImageWithImage:(id)arg1 withIndex:(int)arg2 withImageView:(id)arg3;
- (void)updateDownloadProgress:(double)arg1;
- (void)updatePreViewImagesWith:(id)arg1;
- (void)updateViewWithThemeInfo:(id)arg1;
- (void)createView;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (long long)kw_preferredStatusBarStyle;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithStarThemeInfo:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

