//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "CreatePlaylistViewControllerDelegate-Protocol.h"
#import "KWCellActionDelegate-Protocol.h"
#import "UIDragInteractionDelegate-Protocol.h"
#import "UIDropInteractionDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class BaseTableView, KWCellDownFailedVModel, KWUserPageTaskRequest, NSMutableArray, NSString, NewUserPageBusinessCoordinatorHeaderView, NewUserPageCloudDiskCell, NewUserPageMuiscFeeTipsCell, NewUserPageNaviBarView, NewUserPagePlayListSectionHeaderView, NewUserPageSectionItem, NewUserPageViewBusinessCoordinator, NewUserPageVipCell, UIView;

@interface NewUserPageController : UIViewController <UITableViewDataSource, UITableViewDelegate, UIDragInteractionDelegate, UIDropInteractionDelegate, KWCellActionDelegate, CreatePlaylistViewControllerDelegate>
{
    struct map<NewUserPageSectionEnum, bool, std::__1::less<NewUserPageSectionEnum>, std::__1::allocator<std::__1::pair<const NewUserPageSectionEnum, bool>>> _sectionExpandStatus;
    NewUserPagePlayListSectionHeaderView *_myCreateSheetListheaderView;
    UIView *_myCreateSheetListFooterView;
    NewUserPageSectionItem *_myCreateSheetListItem;
    NewUserPageNaviBarView *_naviBarView;
    UIView *_contentBgView;
    _Bool _motorIsLoad;
    NewUserPageViewBusinessCoordinator *_businessCOordinator;
    NewUserPageBusinessCoordinatorHeaderView *_businessCOordinatorHeaderView;
    KWUserPageTaskRequest *_taskRequst;
    NSMutableArray *_finderMotorList;
    NSMutableArray *_liveMotorList;
    long long _lastUserId;
    _Bool _isDownloading;
    int _loginStatus;
    BaseTableView *_tableView;
    NSMutableArray *_sectionItems;
    NewUserPageVipCell *_vipCell;
    NewUserPageCloudDiskCell *_cloudDisCell;
    NewUserPageMuiscFeeTipsCell *_muiscFeeTipsCell;
    NSString *_songlistRecoverTip;
    KWCellDownFailedVModel *_downFailedVmodel;
}

+ (void)gotoImportSonglistPage:(id)arg1;
@property(nonatomic) _Bool isDownloading; // @synthesize isDownloading=_isDownloading;
@property(retain, nonatomic) KWCellDownFailedVModel *downFailedVmodel; // @synthesize downFailedVmodel=_downFailedVmodel;
@property(copy, nonatomic) NSString *songlistRecoverTip; // @synthesize songlistRecoverTip=_songlistRecoverTip;
@property(retain, nonatomic) NewUserPageMuiscFeeTipsCell *muiscFeeTipsCell; // @synthesize muiscFeeTipsCell=_muiscFeeTipsCell;
@property(retain, nonatomic) NewUserPageCloudDiskCell *cloudDisCell; // @synthesize cloudDisCell=_cloudDisCell;
@property(retain, nonatomic) NewUserPageVipCell *vipCell; // @synthesize vipCell=_vipCell;
@property(nonatomic) int loginStatus; // @synthesize loginStatus=_loginStatus;
@property(retain, nonatomic) NSMutableArray *sectionItems; // @synthesize sectionItems=_sectionItems;
@property(readonly, nonatomic) BaseTableView *tableView; // @synthesize tableView=_tableView;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)checkShowCreatSonglistGuideView;
- (void)handle_LiveCellViewEvent:(int)arg1 businessMotorConfig:(id)arg2 buinessMotorListConfig:(id)arg3;
- (void)handle_NPBOneMotorViewEvent:(int)arg1 motorView:(id)arg2;
- (void)addMotorListView;
- (void)businessMotorList:(int)arg1;
- (_Bool)avoidInvalidOperation;
- (id)sortSectionItems:(id)arg1;
- (void)seperateLiveAndFindMotorList:(id)arg1;
- (void)reload_businessSectionWithList:(id)arg1;
- (_Bool)loadSkin:(struct CSkin *)arg1;
- (void)dropInteraction:(id)arg1 sessionDidExit:(id)arg2;
- (void)dropInteraction:(id)arg1 sessionDidEnter:(id)arg2;
- (void)dropInteraction:(id)arg1 performDrop:(id)arg2;
- (id)dropInteraction:(id)arg1 sessionDidUpdate:(id)arg2;
- (_Bool)dropInteraction:(id)arg1 canHandleSession:(id)arg2;
- (void)dragInteraction:(id)arg1 item:(id)arg2 willAnimateCancelWithAnimator:(id)arg3;
- (void)dragInteraction:(id)arg1 sessionWillBegin:(id)arg2;
- (id)dragInteraction:(id)arg1 previewForLiftingItem:(id)arg2 session:(id)arg3;
- (id)dragInteraction:(id)arg1 itemsForBeginningSession:(id)arg2;
- (void)gotoPlaylistRecovery;
- (void)gotoPlaylistManager;
- (id)getMyCreateSheetList;
- (void)managePlayListButtonAction;
- (void)gotoImportSonglistPage2;
- (void)gotoImportSonglistPage1;
- (void)onPlaylistSectionHeaderViewEvent:(int)arg1;
- (void)createPlaylistViewController:(id)arg1 createPlaylistSuccess:(id)arg2;
- (void)onAddPlaylistButtonTapped;
- (void)setMyCreateSheetListHeaderViewTitle;
- (void)onClickExpandPlaylistButton;
- (void)readSectionExpandStatus;
- (void)saveSectionExpandStatus;
- (void)handlerPlaylistItemsChanged:(id)arg1;
- (void)handlerPlaylistAdded:(id)arg1;
- (void)handlePlaylistNotify:(id)arg1 type:(int)arg2 notifyData:(id)arg3;
- (void)onBoughtRidChanged:(id)arg1;
- (void)onUserLoginNotification:(id)arg1;
- (void)onUserLoginStateChanged:(id)arg1;
- (void)checkHistoryShow;
- (long long)p_downloadCount;
- (long long)p_rencentPlayCount;
- (void)remove_Observers;
- (void)onDownloadEnd:(id)arg1;
- (void)onDownloadBegin:(id)arg1;
- (void)onDownloadFailed:(id)arg1;
- (void)onRecentPlayClear;
- (void)add_Observers;
- (id)findSectionWithType:(int)arg1;
- (void)onClickExpandMyCreateSheetListButton:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 Live_cellForRowAtIndexPath:(id)arg2 sectionType:(int)arg3;
- (id)tableView:(id)arg1 BusinessCoordinator_cellForRowAtIndexPath:(id)arg2 sectionType:(int)arg3;
- (id)tableView:(id)arg1 Playlist_cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)init_muiscFeeTipsCell;
- (void)addTableView;
- (void)viewDidLayoutSubviews;
- (void)addNaviBarView;
- (void)insertDefaultPlaylistInSection:(id)arg1;
- (_Bool)isShowRecoverTip;
- (void)dismissRecoverTIp;
- (void)fetchRecoverStatus;
- (void)insertDefaultPlaylistPCInSection:(id)arg1;
- (long long)indexForPlaylistId:(unsigned long long)arg1 playlistType:(int)arg2;
- (long long)indexForSectionType:(int)arg1;
- (void)reloadMyCreateSheetList;
- (void)sortPostionAboutLiveAndMusicSheeter:(id)arg1;
- (void)reloadThisPageData;
- (void)onVideoReload;
- (id)getCellByClass:(Class)arg1;
- (id)getCellByClassWithoutDeque:(Class)arg1;
- (void)updateVipTaskCellStatus;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)p_showCollectionGuide;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

