//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OnlineItemInfo.h"

@class NSDictionary, NSString;

@interface OnlineAdItemInfo : OnlineItemInfo
{
    NSString *url;
    _Bool inapp;
    _Bool _orientation;
    NSString *_icontext;
    NSDictionary *_extInfo;
    NSString *_shareTitle;
    NSString *_shareUrl;
    NSString *_shareText;
    NSString *_shareImageUrl;
    long long _anchorWhiteList;
}

+ (id)innerLinkItemFromBigsetDict:(id)arg1;
@property(nonatomic) long long anchorWhiteList; // @synthesize anchorWhiteList=_anchorWhiteList;
@property(copy, nonatomic) NSString *shareImageUrl; // @synthesize shareImageUrl=_shareImageUrl;
@property(copy, nonatomic) NSString *shareText; // @synthesize shareText=_shareText;
@property(copy, nonatomic) NSString *shareUrl; // @synthesize shareUrl=_shareUrl;
@property(copy, nonatomic) NSString *shareTitle; // @synthesize shareTitle=_shareTitle;
@property(nonatomic, getter=isOrientation) _Bool orientation; // @synthesize orientation=_orientation;
@property(retain, nonatomic) NSDictionary *extInfo; // @synthesize extInfo=_extInfo;
@property(copy, nonatomic) NSString *icontext; // @synthesize icontext=_icontext;
@property(nonatomic) _Bool inapp; // @synthesize inapp;
@property(copy, nonatomic) NSString *url; // @synthesize url;
- (void).cxx_destruct;
- (_Bool)isAnchorTMEWhiteList;
- (void)dealloc;
- (_Bool)isCompletedWithSectionType:(int)arg1;
- (_Bool)setPropertyWithKey:(const char *)arg1 value:(const char *)arg2;
- (id)init;

@end

