//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class KWSkinCheckBox, UIImageView, UILabel, UIView;

@interface QualityCell : UITableViewCell
{
    _Bool _darkMode;
    _Bool _isLosslessMusic;
    _Bool _isCloudMusic;
    KWSkinCheckBox *_imageViewSel;
    UILabel *_titleLbl;
    UILabel *_detailLbl;
    UIImageView *_imageViewDownload;
    UILabel *_loginTipLbl;
    UIView *_separatorLine;
    UIImageView *_leftIcon;
    UIImageView *_vipIconImageView;
    UIImageView *_musicPackageImageView;
}

@property(retain, nonatomic) UIImageView *musicPackageImageView; // @synthesize musicPackageImageView=_musicPackageImageView;
@property(retain, nonatomic) UIImageView *vipIconImageView; // @synthesize vipIconImageView=_vipIconImageView;
@property(retain, nonatomic) UIImageView *leftIcon; // @synthesize leftIcon=_leftIcon;
@property(retain, nonatomic) UIView *separatorLine; // @synthesize separatorLine=_separatorLine;
@property(nonatomic) _Bool isCloudMusic; // @synthesize isCloudMusic=_isCloudMusic;
@property(nonatomic) _Bool isLosslessMusic; // @synthesize isLosslessMusic=_isLosslessMusic;
@property(retain, nonatomic) UILabel *loginTipLbl; // @synthesize loginTipLbl=_loginTipLbl;
@property(retain, nonatomic) UIImageView *imageViewDownload; // @synthesize imageViewDownload=_imageViewDownload;
@property(retain, nonatomic) UILabel *detailLbl; // @synthesize detailLbl=_detailLbl;
@property(retain, nonatomic) UILabel *titleLbl; // @synthesize titleLbl=_titleLbl;
@property(retain, nonatomic) KWSkinCheckBox *imageViewSel; // @synthesize imageViewSel=_imageViewSel;
@property(nonatomic) _Bool darkMode; // @synthesize darkMode=_darkMode;
- (void).cxx_destruct;
- (void)addLoginTipLbl:(id)arg1;
- (void)layoutSubviews;
- (void)removeAllLabels;
- (void)addDownloadedState;
- (void)showFeeVip:(_Bool)arg1;
- (void)addDetailLbl:(id)arg1;
- (void)addTitleLbl:(id)arg1;
- (void)setIcon:(_Bool)arg1;
- (void)setLine:(_Bool)arg1 withOffset:(double)arg2;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

