//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSDictionary, UIButton, UIImageView;

@interface JKNFloatAdView : UIView
{
    _Bool _isFromDoctor;
    UIImageView *_iconView;
    UIButton *_closeButton;
    NSDictionary *_dataInfo;
}

+ (void)initAdViewOnView:(id)arg1 withData:(id)arg2 fromDoctor:(_Bool)arg3 holdVc:(id)arg4;
@property(nonatomic) _Bool isFromDoctor; // @synthesize isFromDoctor=_isFromDoctor;
@property(copy, nonatomic) NSDictionary *dataInfo; // @synthesize dataInfo=_dataInfo;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
- (void).cxx_destruct;
- (void)onCloseAction:(id)arg1;
- (void)onImageTapped:(id)arg1;
- (void)onPanGestureAction:(id)arg1;
- (void)setupConstraints;
- (id)initWithFrame:(struct CGRect)arg1;

@end

