//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSString, UIButton, UIImageView;

@interface JKNScreenADViewController : UIViewController
{
    _Bool _isFromDoctor;
    NSString *_imgUrl;
    NSString *_pageUrl;
    long long _sceneNo;
    UIImageView *_adImg;
    UIButton *_cancelBtn;
    CDUnknownBlockType _clickHandler;
}

@property(copy, nonatomic) CDUnknownBlockType clickHandler; // @synthesize clickHandler=_clickHandler;
@property(retain, nonatomic) UIButton *cancelBtn; // @synthesize cancelBtn=_cancelBtn;
@property(retain, nonatomic) UIImageView *adImg; // @synthesize adImg=_adImg;
@property(nonatomic) long long sceneNo; // @synthesize sceneNo=_sceneNo;
@property(nonatomic) _Bool isFromDoctor; // @synthesize isFromDoctor=_isFromDoctor;
@property(retain, nonatomic) NSString *pageUrl; // @synthesize pageUrl=_pageUrl;
@property(retain, nonatomic) NSString *imgUrl; // @synthesize imgUrl=_imgUrl;
- (void).cxx_destruct;
- (void)cancelBtnAction;
- (void)imgTapAction:(id)arg1;
- (void)creatUI;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;
- (id)initWithHandler:(CDUnknownBlockType)arg1;

@end

