//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "PARSAdvertPopupViewProtocol-Protocol.h"
#import "PARSAlertViewActivityProtocol-Protocol.h"
#import "PARSDataAnalyticPageViewProtocol-Protocol.h"

@class AVPlayer, AVPlayerLayer, AVPlayerViewController, NSString, PARSAdverInfo, UIButton, YYAnimatedImageView;
@protocol PARSAdvertPopupViewDelegate;

@interface PARSAdvertPopupView : UIView <PARSAdvertPopupViewProtocol, PARSDataAnalyticPageViewProtocol, PARSAlertViewActivityProtocol>
{
    _Bool _popupOnDiscoverHomeVC;
    id <PARSAdvertPopupViewDelegate> _delegate;
    AVPlayer *_player;
    YYAnimatedImageView *_advertImageView;
    UIButton *_closeButton;
    PARSAdverInfo *_advertInfo;
    AVPlayerViewController *_playerVC;
    AVPlayerLayer *_playerLayer;
}

+ (Class)advertPopupViewClass;
@property(retain, nonatomic) AVPlayerLayer *playerLayer; // @synthesize playerLayer=_playerLayer;
@property(retain, nonatomic) AVPlayerViewController *playerVC; // @synthesize playerVC=_playerVC;
@property(retain, nonatomic) PARSAdverInfo *advertInfo; // @synthesize advertInfo=_advertInfo;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) YYAnimatedImageView *advertImageView; // @synthesize advertImageView=_advertImageView;
@property(nonatomic) _Bool popupOnDiscoverHomeVC; // @synthesize popupOnDiscoverHomeVC=_popupOnDiscoverHomeVC;
@property(retain, nonatomic) AVPlayer *player; // @synthesize player=_player;
@property(nonatomic) __weak id <PARSAdvertPopupViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)analyticWithType:(long long)arg1;
- (void)refreshWithVideoUrl:(id)arg1 advertInfo:(id)arg2;
- (void)refreshWithAdvertWebPImg:(id)arg1 advertInfo:(id)arg2;
- (void)refreshWithAdvertImg:(id)arg1 advertInfo:(id)arg2;
- (void)show;
- (id)activityId;
@property(readonly, nonatomic) NSString *pageViewID;
@property(readonly, nonatomic) NSString *pageViewIDAlias;
- (void)disMiss;
- (void)pressCloseBtn;
- (void)advertClick;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

